[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-authbus"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_authbus"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-hepta-types = { path = "../hepta-types" }
ed25519-dalek = { workspace = true }
