[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-authbus"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_authbus"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-hepta-types = { path = "../hepta-types" }
codex-state = { workspace = true }
codex-utils-absolute-path = { workspace = true }
ed25519-dalek = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
