//! Host-supplied H5/H6 shadow-advisory observation.
//!
//! The H5/H6 implementation lives in `codex-hepta-memory` and deliberately
//! stops at a typed, deterministic shadow receipt.  This module is the small
//! extension-facing seam for that receipt.  A host supplies both the immutable
//! input and the receipt; this adapter only validates their binding and keeps
//! a digest-only observation in the host-owned turn [`ExtensionData`].
//!
//! There is intentionally no fallback here.  In particular, this module does
//! not open a KG, derive a snapshot, ask a provider, alter routing, or attach
//! model-visible input.  A missing host attachment is represented as a typed
//! rejection observation so a caller can distinguish "not supplied" from a
//! valid shadow result without treating either one as authority.

use std::sync::Mutex;
use std::sync::PoisonError;

use codex_extension_api::ExtensionData;
use codex_hepta_contracts::Sha256Digest;
use codex_hepta_memory::ShadowAdvisoryError;
use codex_hepta_memory::ShadowAdvisoryInput;
use codex_hepta_memory::ShadowAdvisoryReceipt;
use serde::Deserialize;
use serde::Serialize;
use sha2::Digest;
use sha2::Sha256;

use crate::framing::hash_part;

/// Schema version for the extension observation, independent of the H5/H6
/// receipt schema.  Bump this when the digest-only envelope changes.
pub const HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_SCHEMA_VERSION: u32 = 1;

/// The observation is local-development metadata only.
pub const HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_NAMESPACE: &str = "local_development_only";

/// No observation can authorize an external effect.
pub const SHADOW_ADVISORY_OBSERVATION_EXTERNAL_EFFECTS: bool = false;
/// The observation does not authorize a KG write.
pub const SHADOW_ADVISORY_OBSERVATION_KG_WRITE_AUTHORITY: bool = false;
/// The observation is not a production caller or runtime consumer.
pub const SHADOW_ADVISORY_OBSERVATION_RUNTIME_CONSUMER: bool = false;

const TURN_ID_DOMAIN: &[u8] = b"hepta-memory:shadow-advisory-observation:turn:v1";
const OBSERVATION_DOMAIN: &[u8] = b"hepta-memory:shadow-advisory-observation:v1";

/// Host-owned, typed input for one turn observation.
///
/// Both values must come from the same immutable host read epoch.  The input's
/// `snapshot_digest` is an identity supplied by the host; this type contains no
/// snapshot loader and therefore cannot synthesize a missing KG snapshot.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ShadowAdvisoryObservationInput {
    /// Host turn identity used to bind the attachment to `ExtensionData`.
    pub turn_id: String,
    /// The already-typed H5/H6 input selected by the host.
    pub input: ShadowAdvisoryInput,
    /// The already-computed H5/H6 shadow result selected by the host.
    pub receipt: ShadowAdvisoryReceipt,
}

/// Alias emphasizing that the value is supplied by the host, not generated by
/// this extension.
pub type ShadowAdvisoryHostInput = ShadowAdvisoryObservationInput;

impl ShadowAdvisoryObservationInput {
    /// Builds a host attachment without evaluating or reading anything.
    pub fn new(
        turn_id: impl Into<String>,
        input: ShadowAdvisoryInput,
        receipt: ShadowAdvisoryReceipt,
    ) -> Self {
        Self {
            turn_id: turn_id.into(),
            input,
            receipt,
        }
    }
}

/// Why an observation was not accepted as a valid host-supplied shadow.
///
/// These are deliberately stable, digest-safe categories.  Raw validation
/// errors (and therefore candidate text or other host material) are never
/// retained in `ExtensionData`.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ShadowAdvisoryObservationReason {
    /// The host supplied and bound a valid shadow receipt.
    Observed,
    /// No typed host attachment was present.
    HostInputMissing,
    /// The host attachment names a different turn.
    TurnBindingMismatch,
    /// The H5/H6 input failed validation.
    InputRejected,
    /// The H5/H6 receipt failed validation or recomputation.
    ReceiptRejected,
    /// The supplied receipt asserted an authority that shadow mode forbids.
    AuthorityBoundary,
}

impl ShadowAdvisoryObservationReason {
    fn stable_tag(self) -> &'static str {
        match self {
            Self::Observed => "observed",
            Self::HostInputMissing => "host_input_missing",
            Self::TurnBindingMismatch => "turn_binding_mismatch",
            Self::InputRejected => "input_rejected",
            Self::ReceiptRejected => "receipt_rejected",
            Self::AuthorityBoundary => "authority_boundary",
        }
    }

    fn is_observed(self) -> bool {
        matches!(self, Self::Observed)
    }
}

/// Digest-only metadata retained in one host turn's `ExtensionData`.
///
/// No candidate id, feature key, query, path, principal, installation id, or
/// KG payload is retained here.  Optional fields are populated only for an
/// accepted observation; rejection observations carry the turn digest and a
/// stable reason, never partially trusted material.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ShadowAdvisoryTurnObservation {
    pub schema_version: u32,
    pub namespace: String,
    pub observation_digest: Sha256Digest,
    pub turn_id_sha256: Sha256Digest,
    pub input_digest: Option<Sha256Digest>,
    pub receipt_digest: Option<Sha256Digest>,
    pub state_digest: Option<Sha256Digest>,
    pub snapshot_digest: Option<Sha256Digest>,
    pub policy_digest: Option<Sha256Digest>,
    pub authority_epoch: Option<u64>,
    pub reason: ShadowAdvisoryObservationReason,
    pub production_effects: bool,
    pub execute_allowed: bool,
    pub kg_write_allowed: bool,
    pub online_routing: bool,
    pub runtime_consumer: bool,
}

impl ShadowAdvisoryTurnObservation {
    /// Validates the envelope and its digest without consulting any runtime or
    /// external state.
    pub fn validate(&self) -> Result<(), ShadowAdvisoryObservationError> {
        if self.schema_version != HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_SCHEMA_VERSION
            || self.namespace != HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_NAMESPACE
        {
            return Err(ShadowAdvisoryObservationError::SchemaMismatch);
        }
        validate_digest(&self.observation_digest)?;
        validate_digest(&self.turn_id_sha256)?;
        for digest in [
            self.input_digest.as_ref(),
            self.receipt_digest.as_ref(),
            self.state_digest.as_ref(),
            self.snapshot_digest.as_ref(),
            self.policy_digest.as_ref(),
        ]
        .into_iter()
        .flatten()
        {
            validate_digest(digest)?;
        }
        if self.production_effects
            || self.execute_allowed
            || self.kg_write_allowed
            || self.online_routing
            || self.runtime_consumer
        {
            return Err(ShadowAdvisoryObservationError::AuthorityBoundary);
        }
        let complete = self.input_digest.is_some()
            && self.receipt_digest.is_some()
            && self.state_digest.is_some()
            && self.snapshot_digest.is_some()
            && self.policy_digest.is_some()
            && self.authority_epoch.is_some();
        if self.reason.is_observed() != complete {
            return Err(ShadowAdvisoryObservationError::IncompleteObservation);
        }
        if self.authority_epoch == Some(0) {
            return Err(ShadowAdvisoryObservationError::Invalid(
                "authority epoch must be non-zero".to_string(),
            ));
        }
        if self.observation_digest != observation_digest(self) {
            return Err(ShadowAdvisoryObservationError::DigestMismatch);
        }
        Ok(())
    }

    /// Returns whether this value is a local, non-authoritative observation.
    pub fn is_shadow_only(&self) -> bool {
        self.namespace == HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_NAMESPACE
            && !self.production_effects
            && !self.execute_allowed
            && !self.kg_write_allowed
            && !self.online_routing
            && !self.runtime_consumer
    }

    fn rejected(turn_id: &str, reason: ShadowAdvisoryObservationReason) -> Self {
        let mut observation = Self {
            schema_version: HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_SCHEMA_VERSION,
            namespace: HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_NAMESPACE.to_string(),
            observation_digest: Sha256Digest::for_bytes(b"pending"),
            turn_id_sha256: turn_digest(turn_id),
            input_digest: None,
            receipt_digest: None,
            state_digest: None,
            snapshot_digest: None,
            policy_digest: None,
            authority_epoch: None,
            reason,
            production_effects: SHADOW_ADVISORY_OBSERVATION_EXTERNAL_EFFECTS,
            execute_allowed: false,
            kg_write_allowed: SHADOW_ADVISORY_OBSERVATION_KG_WRITE_AUTHORITY,
            online_routing: false,
            runtime_consumer: SHADOW_ADVISORY_OBSERVATION_RUNTIME_CONSUMER,
        };
        observation.observation_digest = observation_digest(&observation);
        observation
    }

    fn accepted(
        turn_id: &str,
        host_input: &ShadowAdvisoryObservationInput,
    ) -> Result<Self, ShadowAdvisoryObservationReason> {
        if host_input.turn_id != turn_id
            || host_input.turn_id.trim().is_empty()
            || host_input.turn_id.len() > 256
            || host_input.turn_id.chars().any(char::is_control)
        {
            return Err(ShadowAdvisoryObservationReason::TurnBindingMismatch);
        }
        if let Err(error) = host_input.input.validate() {
            return Err(match error {
                ShadowAdvisoryError::AuthorityBoundary => {
                    ShadowAdvisoryObservationReason::AuthorityBoundary
                }
                _ => ShadowAdvisoryObservationReason::InputRejected,
            });
        }
        if let Err(error) = host_input.receipt.validate_against(&host_input.input) {
            return Err(match error {
                ShadowAdvisoryError::AuthorityBoundary => {
                    ShadowAdvisoryObservationReason::AuthorityBoundary
                }
                _ => ShadowAdvisoryObservationReason::ReceiptRejected,
            });
        }
        let input_digest = host_input
            .input
            .digest()
            .map_err(|_| ShadowAdvisoryObservationReason::InputRejected)?;
        let mut observation = Self {
            schema_version: HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_SCHEMA_VERSION,
            namespace: HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_NAMESPACE.to_string(),
            observation_digest: Sha256Digest::for_bytes(b"pending"),
            turn_id_sha256: turn_digest(turn_id),
            input_digest: Some(input_digest),
            receipt_digest: Some(host_input.receipt.receipt_digest.clone()),
            state_digest: Some(host_input.input.state_digest.clone()),
            snapshot_digest: Some(host_input.input.snapshot_digest.clone()),
            policy_digest: Some(host_input.input.policy_digest.clone()),
            authority_epoch: Some(host_input.input.authority_epoch),
            reason: ShadowAdvisoryObservationReason::Observed,
            production_effects: SHADOW_ADVISORY_OBSERVATION_EXTERNAL_EFFECTS,
            execute_allowed: false,
            kg_write_allowed: SHADOW_ADVISORY_OBSERVATION_KG_WRITE_AUTHORITY,
            online_routing: false,
            runtime_consumer: SHADOW_ADVISORY_OBSERVATION_RUNTIME_CONSUMER,
        };
        observation.observation_digest = observation_digest(&observation);
        Ok(observation)
    }
}

#[derive(Debug)]
struct ShadowAdvisoryTurnObservationSlot {
    observation: Mutex<Option<ShadowAdvisoryTurnObservation>>,
}

/// Errors returned when an observation cannot be accepted into the seam.
#[derive(Debug, Eq, PartialEq)]
pub enum ShadowAdvisoryObservationError {
    Rejected(ShadowAdvisoryObservationReason),
    SchemaMismatch,
    DigestMismatch,
    IncompleteObservation,
    Invalid(String),
    AuthorityBoundary,
    Conflict,
}

impl std::fmt::Display for ShadowAdvisoryObservationError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected(reason) => {
                write!(
                    formatter,
                    "shadow advisory host input was rejected: {reason:?}"
                )
            }
            Self::SchemaMismatch => {
                formatter.write_str("shadow advisory observation schema is not supported")
            }
            Self::DigestMismatch => formatter
                .write_str("shadow advisory observation digest does not match its contents"),
            Self::IncompleteObservation => {
                formatter.write_str("shadow advisory observation is incomplete")
            }
            Self::Invalid(detail) => write!(
                formatter,
                "shadow advisory observation is invalid: {detail}"
            ),
            Self::AuthorityBoundary => {
                formatter.write_str("shadow advisory observation crosses the authority boundary")
            }
            Self::Conflict => formatter.write_str(
                "shadow advisory observation conflicts with an existing turn observation",
            ),
        }
    }
}

impl std::error::Error for ShadowAdvisoryObservationError {}

/// Returns the immutable digest-only observation retained for this turn.
pub fn shadow_advisory_turn_observation(
    turn_store: &ExtensionData,
) -> Option<ShadowAdvisoryTurnObservation> {
    let slot = turn_store.get::<ShadowAdvisoryTurnObservationSlot>()?;
    slot.observation
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .clone()
}

/// Reads a host-seeded [`ShadowAdvisoryObservationInput`] and records its
/// digest-only observation.
///
/// The host may seed the value with `ExtensionDataInit` before constructing the
/// turn store.  This function is deliberately explicit and is not registered
/// as a turn/runtime contributor in this slice.
pub fn observe_shadow_advisory(
    turn_store: &ExtensionData,
) -> Result<ShadowAdvisoryTurnObservation, ShadowAdvisoryObservationError> {
    let Some(host_input) = turn_store.get::<ShadowAdvisoryObservationInput>() else {
        return record_observation(
            turn_store,
            ShadowAdvisoryTurnObservation::rejected(
                turn_store.level_id(),
                ShadowAdvisoryObservationReason::HostInputMissing,
            ),
        );
    };
    observe_shadow_advisory_input(turn_store, host_input.as_ref())
}

/// Records a host-supplied typed input without writing that input into the
/// store.  The store receives only the digest-only observation.
pub fn observe_shadow_advisory_input(
    turn_store: &ExtensionData,
    host_input: &ShadowAdvisoryObservationInput,
) -> Result<ShadowAdvisoryTurnObservation, ShadowAdvisoryObservationError> {
    let observation =
        match ShadowAdvisoryTurnObservation::accepted(turn_store.level_id(), host_input) {
            Ok(observation) => observation,
            Err(reason) => ShadowAdvisoryTurnObservation::rejected(turn_store.level_id(), reason),
        };
    record_observation(turn_store, observation)
}

/// Strict helper for hosts that want a rejected observation surfaced as an
/// error while still retaining the typed digest-only rejection in
/// `ExtensionData`.
pub fn require_shadow_advisory_observation(
    turn_store: &ExtensionData,
) -> Result<ShadowAdvisoryTurnObservation, ShadowAdvisoryObservationError> {
    observe_shadow_advisory(turn_store)
}

fn record_observation(
    turn_store: &ExtensionData,
    observation: ShadowAdvisoryTurnObservation,
) -> Result<ShadowAdvisoryTurnObservation, ShadowAdvisoryObservationError> {
    let reason = observation.reason;
    let committed = commit_observation(turn_store, observation)?;
    if !reason.is_observed() {
        return Err(ShadowAdvisoryObservationError::Rejected(reason));
    }
    Ok(committed)
}

fn commit_observation(
    turn_store: &ExtensionData,
    observation: ShadowAdvisoryTurnObservation,
) -> Result<ShadowAdvisoryTurnObservation, ShadowAdvisoryObservationError> {
    observation.validate()?;
    let slot = turn_store.get_or_init(|| ShadowAdvisoryTurnObservationSlot {
        observation: Mutex::new(None),
    });
    let mut stored = slot
        .observation
        .lock()
        .unwrap_or_else(PoisonError::into_inner);
    match stored.as_ref() {
        None => {
            *stored = Some(observation.clone());
            Ok(observation)
        }
        Some(existing) if existing == &observation => Ok(existing.clone()),
        Some(_) => Err(ShadowAdvisoryObservationError::Conflict),
    }
}

fn turn_digest(turn_id: &str) -> Sha256Digest {
    let mut hasher = Sha256::new();
    hash_part(&mut hasher, TURN_ID_DOMAIN);
    hash_part(&mut hasher, turn_id.as_bytes());
    Sha256Digest::for_bytes(&hasher.finalize())
}

fn observation_digest(observation: &ShadowAdvisoryTurnObservation) -> Sha256Digest {
    let mut hasher = Sha256::new();
    hash_part(&mut hasher, OBSERVATION_DOMAIN);
    hash_part(&mut hasher, &observation.schema_version.to_be_bytes());
    hash_part(&mut hasher, observation.namespace.as_bytes());
    hash_part(&mut hasher, observation.turn_id_sha256.as_str().as_bytes());
    hash_part(&mut hasher, observation.reason.stable_tag().as_bytes());
    hash_optional_digest(&mut hasher, observation.input_digest.as_ref());
    hash_optional_digest(&mut hasher, observation.receipt_digest.as_ref());
    hash_optional_digest(&mut hasher, observation.state_digest.as_ref());
    hash_optional_digest(&mut hasher, observation.snapshot_digest.as_ref());
    hash_optional_digest(&mut hasher, observation.policy_digest.as_ref());
    match observation.authority_epoch {
        Some(epoch) => {
            hash_part(&mut hasher, b"epoch");
            hash_part(&mut hasher, &epoch.to_be_bytes());
        }
        None => hash_part(&mut hasher, b"epoch:none"),
    }
    hash_part(
        &mut hasher,
        &[
            u8::from(observation.production_effects),
            u8::from(observation.execute_allowed),
            u8::from(observation.kg_write_allowed),
            u8::from(observation.online_routing),
            u8::from(observation.runtime_consumer),
        ],
    );
    Sha256Digest::for_bytes(&hasher.finalize())
}

fn hash_optional_digest(hasher: &mut Sha256, digest: Option<&Sha256Digest>) {
    match digest {
        Some(digest) => {
            hash_part(hasher, b"digest");
            hash_part(hasher, digest.as_str().as_bytes());
        }
        None => hash_part(hasher, b"digest:none"),
    }
}

fn validate_digest(digest: &Sha256Digest) -> Result<(), ShadowAdvisoryObservationError> {
    Sha256Digest::parse(digest.as_str().to_string()).map_err(|_| {
        ShadowAdvisoryObservationError::Invalid(
            "digest must be a lowercase SHA-256 digest".to_string(),
        )
    })?;
    Ok(())
}

#[cfg(test)]
#[path = "advisory_observation_tests.rs"]
mod tests;
