//! Per-agent process lifecycle control for the Hepta workspace fleet.
//!
//! The supervisor does not execute turns or forward messages, models, or tokens.

mod authority_signer;
mod control;
mod daemon;
mod daemon_client;
mod daemon_protocol;
mod driver;
mod error;
mod lease;
mod matrix;
mod model;
mod recovery;
mod release;
mod robrix_projection;
mod robrix_protocol;
mod runtime;
mod signed_authority;
mod signed_intent;
mod supervisor;
mod supervisor_qualification;
mod tick;

#[cfg(unix)]
mod unix;

pub use authority_signer::ExternalSignerError;
pub use authority_signer::MAX_SIGNING_KEY_INPUT_BYTES;
pub use authority_signer::MAX_SIGNING_REQUEST_BYTES;
pub use authority_signer::SignRequest;
pub use authority_signer::SignResponse;
pub use authority_signer::load_signing_key_from_fd;
pub use authority_signer::load_signing_key_from_path;
pub use authority_signer::read_request;
pub use authority_signer::sign_request;
pub use daemon::PRODUCTION_AUTHORITY_FEATURE_ENABLED;
pub use daemon::run_supervisord;
pub use daemon::run_supervisord_with_grant_verifier;
pub use daemon_client::SupervisordClient;
pub use daemon_protocol::ControlStateDigest;
pub use daemon_protocol::MAX_SUPERVISORD_ROSTER;
pub use daemon_protocol::SUPERVISORD_CONTROL_SCHEMA_VERSION;
pub use daemon_protocol::SupervisorEpoch;
pub use daemon_protocol::SupervisordAgentStatus;
pub use daemon_protocol::SupervisordControlFence;
pub use daemon_protocol::SupervisordHealth;
pub use daemon_protocol::SupervisordMatrixStatus;
pub use daemon_protocol::SupervisordMethod;
pub use daemon_protocol::SupervisordMutation;
pub use daemon_protocol::SupervisordMutationAccepted;
pub use daemon_protocol::SupervisordPayload;
pub use daemon_protocol::SupervisordRequest;
pub use daemon_protocol::SupervisordRequestValidationError;
pub use daemon_protocol::SupervisordResponse;
pub use driver::AdoptSpec;
pub use driver::Adoption;
pub use driver::ManagedProcess;
pub use driver::MatrixAdoptSpec;
pub use driver::MatrixSpawnSpec;
pub use driver::ProcessDriver;
pub use driver::ProcessObservation;
pub use driver::ProcessState;
pub use driver::SpawnSpec;
pub use driver::SpawnedProcess;
pub use error::ProcessDriverError;
pub use error::SupervisorError;
pub use model::AgentCommand;
pub use model::AgentFault;
pub use model::AgentRelease;
pub use model::AgentSupervisorSnapshot;
pub(crate) use model::ControlReleaseChange;
pub(crate) use model::ControlReleaseChangePhase;
pub(crate) use model::ControlRuntimePhase;
pub use model::MatrixSupervisorSnapshot;
pub use model::ProcessExit;
pub use model::ProcessIdentity;
pub use model::ProcessLog;
pub use model::ProcessStream;
pub use model::SupervisorConfig;
pub use model::SupervisorEvent;
pub use model::SupervisorEventKind;
pub use model::TickReport;
pub use robrix_projection::CORPUS_FILE;
pub use robrix_projection::GENERATED_CONSTANTS_FILE;
pub use robrix_projection::MANIFEST_FILE;
pub use robrix_projection::MATRIXD_SCHEMA_FILE;
pub use robrix_projection::ROBRIX_CONTROL_PROJECTION_SCHEMA_VERSION;
pub use robrix_projection::SUPERVISORD_SCHEMA_FILE;
pub use robrix_projection::generated_robrix_control_artifacts;
pub use robrix_projection::verify_robrix_control_corpus;
pub use robrix_projection::write_robrix_control_projection;
pub use robrix_protocol::ROBRIX_SUPERVISORD_ALLOWED_METHODS;
pub use robrix_protocol::RobrixProtocolError;
pub use robrix_protocol::RobrixSupervisordMethod;
pub use robrix_protocol::RobrixSupervisordPayload;
pub use robrix_protocol::RobrixSupervisordRequest;
pub use robrix_protocol::RobrixSupervisordResponse;
pub use signed_authority::H7H89ProductionGrant;
pub use signed_authority::H7H89ProductionGrantSigner;
pub use signed_authority::H7H89ProductionGrantVerifier;
pub use signed_authority::H7H89ProductionTransition;
pub use signed_authority::ProductionMutationReceipt;
pub use signed_authority::ProductionMutationStatus;
pub use signed_authority::SIGNED_AUTHORITY_NAMESPACE;
pub use signed_authority::SIGNED_AUTHORITY_SCHEMA_VERSION;
pub use signed_authority::authority_epoch_for_supervisor_epoch;
pub use supervisor::Supervisor;
pub use supervisor_qualification::H8_H9_SHADOW_EFFECT_AUTHORITY;
pub use supervisor_qualification::H8_H9_SHADOW_EXECUTE_ALLOWED;
pub use supervisor_qualification::H8_H9_SHADOW_EXTERNAL_EFFECTS;
pub use supervisor_qualification::H8_H9_SHADOW_G5_ALLOWED;
pub use supervisor_qualification::H8_H9_SHADOW_GOVERNANCE_BYPASS;
pub use supervisor_qualification::H8_H9_SHADOW_NAMESPACE;
pub use supervisor_qualification::H8_H9_SHADOW_OPERATOR_ACCEPTANCE;
pub use supervisor_qualification::H8_H9_SHADOW_PRODUCTION_AUTHORITY;
pub use supervisor_qualification::H8_H9_SHADOW_PRODUCTION_CALLER;
pub use supervisor_qualification::H8_H9_SHADOW_PRODUCTION_WRITER;
pub use supervisor_qualification::H8_H9_SHADOW_PROMOTION;
pub use supervisor_qualification::H8_H9_SHADOW_PROMOTION_ELIGIBLE;
pub use supervisor_qualification::H8_H9_SHADOW_SCHEMA_VERSION;
pub use supervisor_qualification::H8H9PendingRollback;
pub use supervisor_qualification::H8H9RecoveryOutcome;
pub use supervisor_qualification::H8H9RollbackPhase;
pub use supervisor_qualification::H8H9ShadowSupervisor;
pub use supervisor_qualification::H8H9SupervisorError;
pub use supervisor_qualification::H8H9SupervisorState;
pub use supervisor_qualification::H8ShadowSupervisor;
pub use supervisor_qualification::H9ShadowRollbackMachine;
pub use supervisor_qualification::QualificationSupervisor;

#[cfg(unix)]
pub use unix::UnixManagedProcess;
#[cfg(unix)]
pub use unix::UnixProcessDriver;
