// @generated by codex-hepta-supervisor; do not edit by hand.
pub(crate) const ROBRIX_CONTROL_PROJECTION_SCHEMA_VERSION: u32 = 1;
pub(crate) const ROBRIX_SUPERVISORD_SCHEMA_VERSION: u32 = 2;
pub(crate) const ROBRIX_SUPERVISORD_MAX_FRAME_BYTES: usize = 65536;
pub(crate) const ROBRIX_SUPERVISORD_MAX_ROSTER: u16 = 256;
pub(crate) const ROBRIX_SUPERVISORD_ALLOWED_METHODS: [&str; 3] = ["health", "roster", "snapshot"];
pub(crate) const MATRIXD_CONTROL_SCHEMA_VERSION: u32 = 2;
pub(crate) const MAX_MATRIXD_CONTROL_FRAME_BYTES: usize = 1048576;
pub(crate) const MAX_MATRIXD_EVENT_BATCH: u16 = 256;
pub(crate) const MAX_PENDING_APPROVALS: usize = 256;
pub(crate) const MAX_PENDING_APPROVAL_SUMMARY_BYTES: usize = 1024;
pub(crate) const MAX_RUNTIME_IDENTIFIER_BYTES: usize = 512;
pub(crate) const MAX_MATRIXD_ERROR_CODE_BYTES: usize = 64;
pub(crate) const MAX_MATRIXD_ERROR_MESSAGE_BYTES: usize = 1024;
pub(crate) const ROBRIX_REQUIRED_JSON_SCHEMA_KEYWORDS: [&str; 2] = ["x-hepta-max-utf8-bytes", "x-hepta-safe-text-profile"];
pub(crate) const MATRIXD_BOOTSTRAP_METHODS: [&str; 2] = ["health", "snapshot"];
pub(crate) const MATRIXD_FENCED_METHODS: [&str; 3] = ["events", "cancel_turn", "resolve_approval"];
