//! Append-only causal learning facts with independent outcomes and revocation
//! lineage.
//!
//! The pure core owns no ambient I/O or execution authority. An opt-in durable
//! adapter writes only learning facts through a host-authorized file handle;
//! it grants no model, tool, network, selection, promotion or release authority.

#![forbid(unsafe_code)]

mod causal_v2;
mod checkpoint;
mod dataset_receipt_v3;
mod durable;
mod durable_codec;
mod durable_lock;
mod error;
mod journal;
mod ledger;
mod model;
mod production;
mod protocol;
mod segment_codec;
mod segments;
mod shadow;
mod signed_evidence;
mod trust_distribution;
mod witness;

pub use causal_v2::AuthenticatedOutcomeV1;
pub use causal_v2::AuthenticatedPrincipalV1;
pub use causal_v2::CandidateSetCompletenessReceiptV1;
pub use causal_v2::CausalV2Error;
pub use causal_v2::CreditAllocationBatchV1;
pub use causal_v2::CreditAllocationReceiptV1;
pub use causal_v2::CreditAllocationV1;
pub use causal_v2::DatasetFreezeRequestV1;
pub use causal_v2::DatasetSnapshotV2;
pub use causal_v2::OutcomeTerminalityV1;
pub use causal_v2::OutcomeWatermarkV1;
pub use causal_v2::finalize_credit_batch;
pub use causal_v2::freeze_dataset;
pub use causal_v2::validate_authenticated_outcome;
pub use causal_v2::validate_candidate_set_completeness;
pub use causal_v2::verify_independent_roles;
pub use checkpoint::LedgerCheckpointError;
pub use checkpoint::LedgerIndexCheckpointV1;
pub use checkpoint::LedgerIndexEntryV1;
pub use checkpoint::OutcomeHeadIndexV1;
pub use checkpoint::build_ledger_index_checkpoint;
pub use checkpoint::verify_ledger_index_checkpoint;
pub use dataset_receipt_v3::DatasetReceiptError;
pub use dataset_receipt_v3::DatasetSnapshotReceiptV3;
pub use dataset_receipt_v3::freeze_dataset_receipt_v3;
pub use dataset_receipt_v3::verify_dataset_snapshot_receipt_v3;
pub use durable::DurableLedger;
pub use durable::DurableLedgerError;
pub use durable::LedgerAnchor;
pub use durable::LedgerRecovery;
pub use durable::inspect_ledger;
pub use error::LedgerError;
pub use journal::DurableLearningJournal;
pub use ledger::LearningLedger;
pub use model::AppendDisposition;
pub use model::AppendReceipt;
pub use model::AuthenticatedDecisionRecordV2;
pub use model::AuthenticatedOutcomeRecordV2;
pub use model::AuthenticatedOutcomeTerminality;
pub use model::CandidateSetCompleteness;
pub use model::CreditAllocationBatchRecordV2;
pub use model::CreditAllocationRecordV2;
pub use model::CreditAssignment;
pub use model::EpisodeDecision;
pub use model::LedgerEvent;
pub use model::LedgerRecord;
pub use model::LedgerSnapshot;
pub use model::OutcomeFinality;
pub use model::OutcomeObservation;
pub use model::Revocation;
pub use model::UnlearningLineageEventV1;
pub use production::DatasetFreezePlanV2;
pub use production::LedgerWriter;
pub use production::ProductionDecisionV2;
pub use production::ProductionLedgerError;
pub use production::UnlearningLineageReceiptV1;
pub use production::UnlearningLineageRequestV1;
pub use production::candidate_ids_digest_v2;
pub use production::candidate_order_digest_v2;
pub use production::credit_batch_signing_payload_v2;
pub use production::dataset_freeze_signing_payload_v2;
pub use production::decision_signing_payload_v2;
pub use production::freeze_dataset_from_ledger;
pub use production::outcome_signing_payload_v2;
pub use production::unlearning_signing_payload_v1;
pub use protocol::CreditAllocationV1 as CreditAllocationProtocolV1;
pub use protocol::CreditAssignmentReceiptV1;
pub use protocol::DatasetSnapshotV1;
pub use protocol::EpisodeTerminalityV1;
pub use protocol::LearningDecisionV1;
pub use protocol::LearningEpisodeV1;
pub use protocol::LearningProtocolError;
pub use protocol::OutcomeCensoringV1;
pub use protocol::OutcomeReceiptV1;
pub use protocol::OutcomeWatermarkProtocolV1;
pub use protocol::OutcomeWatermarkTerminalityV1;
pub use protocol::decode_credit_assignment_receipt_v1;
pub use protocol::decode_dataset_snapshot_v1;
pub use protocol::decode_learning_decision_v1;
pub use protocol::decode_learning_episode_v1;
pub use protocol::decode_outcome_receipt_v1;
pub use protocol::encode_credit_assignment_receipt_v1;
pub use protocol::encode_dataset_snapshot_v1;
pub use protocol::encode_learning_decision_v1;
pub use protocol::encode_learning_episode_v1;
pub use protocol::encode_outcome_receipt_v1;
pub use segments::LedgerSegmentCheckpoint;
pub use segments::LedgerSegmentLimits;
pub use segments::MAX_LEDGER_SEGMENTS;
pub use segments::SegmentedLedger;
pub use segments::inspect_ledger_segments;
pub use shadow::ShadowAppendReceipt;
pub use shadow::ShadowDecisionArtifact;
pub use shadow::ShadowDecisionError;
pub use shadow::ShadowDecisionRequest;
pub use shadow::append_shadow_decision;
pub use shadow::canonical_candidate_set_digest;
pub use shadow::prepare_shadow_decision;
pub use signed_evidence::LearningEvidenceRoleV1;
pub use signed_evidence::LearningEvidenceTrustV1;
pub use signed_evidence::LearningEvidenceVerifierV1;
pub use signed_evidence::SignedEvidenceError;
pub use signed_evidence::SignedLearningEvidenceV1;
pub use signed_evidence::TrustedLearningSignerV1;
pub use signed_evidence::VerifiedLearningEvidenceV1;
pub use signed_evidence::verify_signed_role_separation;
pub use trust_distribution::ActivatedLearningTrustV1;
pub use trust_distribution::LearningTrustDistributionError;
pub use trust_distribution::LearningTrustDistributionV1;
pub use trust_distribution::activate_learning_trust;
pub use witness::LedgerWitnessFrontier;
pub use witness::LedgerWitnessStore;

#[cfg(test)]
#[path = "shadow_tests.rs"]
mod shadow_tests;
