// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeptaHistoricalEvidenceFamily } from "./HeptaHistoricalEvidenceFamily";
import type { HeptaHistoricalEvidenceState } from "./HeptaHistoricalEvidenceState";

export type HeptaHistoricalEvidenceRecord = { schemaVersion: number, family: HeptaHistoricalEvidenceFamily, recordId: string, state: HeptaHistoricalEvidenceState, evidenceSha256: string, recordSha256: string, };
