// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadStartResponse } from "./ThreadStartResponse";

export type ThreadCreationObserveOutcome = { "type": "pending", threadId: string, } | { "type": "materialized", threadId: string, } | { "type": "created", response: ThreadStartResponse, } | { "type": "deleted", threadId: string, } | { "type": "abandoned", threadId: string, } | { "type": "missing" } | { "type": "unknown" };
