// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadQueueObservedTerminal } from "./ThreadQueueObservedTerminal";

export type ThreadQueueObserveOutcome = { "type": "pending", queuedSubmissionId: string | null, } | { "type": "persisted", turnId: string, terminal: ThreadQueueObservedTerminal | null, } | { "type": "missing" } | { "type": "unknown" } | { "type": "cancelled" };
