// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All bindings must match the request before a native caller may cross an
 * effect boundary. Unsupported servers cannot provide this positive V1 ACK.
 */
export type ThreadEphemeralRetainResponse = { protocolVersion: number, threadId: string, sessionId: string, operationId: string, };
