// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadEphemeralDisposalParams } from "./ThreadEphemeralDisposalParams";

export type ThreadUnsubscribeParams = { threadId: string,
/**
 * Explicit disposal of an idle ephemeral runtime. Omitted/null keeps the
 * ordinary unsubscribe and idle-cache behavior.
 */
ephemeralDisposal?: ThreadEphemeralDisposalParams | null, };
