// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opt-in V1 residency until explicit exact-session disposal. This grants no
 * execution, terminal observation or history-deletion authority.
 */
export type ThreadEphemeralRetainParams = { protocolVersion: number, threadId: string, expectedSessionId: string, operationId: string, };
