// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resume an interrupted turn without submitting new user input.
 */
export type TurnRecoverParams = {
/**
 * Thread that owns the interrupted turn.
 */
threadId: string,
/**
 * Identifier of the interrupted turn to resume.
 */
turnId: string, };
