// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

/**
 * The recovered turn, preserving the original turn identity and current status.
 */
export type TurnRecoverResponse = { turn: Turn, };
