[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-intuition"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_intuition"
path = "src/lib.rs"
doctest = false

[[bench]]
name = "intuition_fast"
harness = false

[lints]
workspace = true

[dependencies]
base64.workspace = true
codex-hepta-types = { path = "../hepta-types" }
ed25519-dalek.workspace = true

[dev-dependencies]
divan.workspace = true
