[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-inferd"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_inferd"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-hepta-contracts = { workspace = true }
codex-hepta-infer-core = { path = "../hepta-infer-core" }
codex-hepta-infer-worker-host = { path = "../hepta-infer-worker-host" }
codex-hepta-types = { path = "../hepta-types" }
tokio-util = { workspace = true }
