//! Immutable learning artifact and lineage registry.
//!
//! Registry eligibility is not selection, activation, promotion or release.
//! This crate deliberately exposes no API capable of granting those powers.

#![forbid(unsafe_code)]

mod admin;
mod admission_v3;
mod cell_split;
#[cfg(test)]
#[path = "cell_split_tests.rs"]
mod cell_split_tests;
mod closure_v2;
mod dataset_revocation;
mod decision_owner;
mod durable_definition;
mod durable_snapshots;
mod durable_state;
mod error;
mod iteration;
mod iteration_ledger;
mod learned_owner;
mod lifecycle_journal;
mod limits;
mod memory_read;
mod memory_read_cas;
mod memory_read_qualification;
mod model;
mod owner_host;
mod owner_service;
mod pinned;
mod plasticity_owner;
mod production_owner;
mod publication;
mod qualification_owner;
mod registry;
mod selection;
mod sensor_core_registry;
mod storage;
mod storage_hygiene;
#[cfg(test)]
mod test_support;
mod typed_role;

pub use admin::ArtifactOwnerStatusV1;
pub use admin::inspect_artifact_owner_status_v1;
pub use admission_v3::ArtifactAdmissionError;
pub use admission_v3::WithdrawalBoundArtifactAdmissionV3;
pub use admission_v3::admit_manifest_at_withdrawal_head_v3;
pub use admission_v3::validate_artifact_publication_v3;
pub use admission_v3::verify_artifact_admission_v3;
pub use cell_split::CellArtifactCasReceiptV1;
pub use cell_split::CellArtifactOwnerErrorV1;
pub use cell_split::CellArtifactPublicationReceiptV1;
pub use cell_split::CellArtifactPublicationStateV1;
pub use cell_split::CellArtifactPublicationV1;
pub use cell_split::CellArtifactRegistryReceiptV1;
pub use cell_split::CellParameterBundleManifestV1;
pub use cell_split::CellParameterBundleMaterializationV1;
pub use cell_split::MAX_CELL_ARTIFACT_CHILDREN_V1;
pub use closure_v2::ArtifactClosureError;
pub use closure_v2::ArtifactLifecycleEventV1;
pub use closure_v2::ArtifactLifecycleStateV1;
pub use closure_v2::DatasetWithdrawalNoticeV1;
pub use closure_v2::DatasetWithdrawalReceiptV1;
pub use closure_v2::DatasetWithdrawalRecordV1;
pub use closure_v2::DatasetWithdrawalRegistry;
pub use closure_v2::DatasetWithdrawalRegistrySnapshotV1;
pub use closure_v2::DatasetWithdrawalScopeV1;
pub use closure_v2::LearningArtifactManifestV2;
pub use closure_v2::ProvenanceModeV1;
pub use closure_v2::RegistryHeadReceiptV1;
pub use closure_v2::RegistryHeadRequirementV1;
pub use closure_v2::RegistryHeadWitnessV1;
pub use closure_v2::ValidatedArtifactManifestV2;
pub use closure_v2::WithdrawalAppendDispositionV1;
pub use closure_v2::validate_artifact_lifecycle_transition;
pub use closure_v2::validate_artifact_manifest_v2;
pub use closure_v2::validate_registry_head_witness;
pub use dataset_revocation::DatasetRevocationError;
pub use dataset_revocation::DatasetRevocationRequest;
pub use dataset_revocation::DatasetRevocationSummary;
pub use dataset_revocation::PreparedDatasetRevocation;
pub use dataset_revocation::prepare_dataset_revocation;
pub use decision_owner::DecisionArtifactLoadReceiptV1;
pub use decision_owner::DecisionCellOwnerErrorV1;
pub use decision_owner::DecisionCellOwnerV1;
pub use decision_owner::DecisionCellPhaseV1;
pub use decision_owner::DecisionPolicyArtifactBindingV1;
pub use decision_owner::DecisionRollbackReceiptV1;
pub use decision_owner::DecisionStateRecoveryReceiptV1;
pub use decision_owner::DecisionTombstoneReceiptV1;
pub use decision_owner::decision_policy_artifact_payload_v1;
pub use durable_definition::DurableCellDefinitionOwnerV1;
pub use durable_definition::DurableDefinitionOwnerError;
pub use durable_snapshots::ArtifactLifecycleSnapshotReceiptV2;
pub use durable_snapshots::DatasetWithdrawalSnapshotReceiptV1;
pub use durable_snapshots::read_artifact_lifecycle_snapshot;
pub use durable_snapshots::read_dataset_withdrawal_snapshot;
pub use durable_snapshots::write_artifact_lifecycle_snapshot;
pub use durable_snapshots::write_artifact_lifecycle_snapshot_beneath;
pub use durable_snapshots::write_dataset_withdrawal_snapshot;
pub use durable_snapshots::write_dataset_withdrawal_snapshot_beneath;
pub use durable_state::DurableStateError;
pub use durable_state::DurableStateOwnerV1;
pub use error::ArtifactRegistryError;
pub use iteration::IterationCandidateStateV1;
pub use iteration::IterationCandidateV1;
pub use iteration::IterationEnvelopeV1;
pub use iteration::validate_iteration_transition;
pub use iteration_ledger::IterationEvidenceKindV1;
pub use iteration_ledger::IterationEvidenceV1;
pub use iteration_ledger::IterationLedgerError;
pub use iteration_ledger::IterationLedgerEventV1;
pub use iteration_ledger::IterationLedgerSnapshotV1;
pub use iteration_ledger::IterationLedgerV1;
pub use iteration_ledger::MAX_ITERATION_EVENTS;
pub use learned_owner::DURABLE_LEARNED_ROLE_OWNER_SCHEMA_V1;
pub use learned_owner::DurableLearnedRoleOwnerErrorV1;
pub use learned_owner::DurableLearnedRoleOwnerV1;
pub use lifecycle_journal::ArtifactLifecycleJournalError;
pub use lifecycle_journal::ArtifactLifecycleJournalReceiptV2;
pub use lifecycle_journal::ArtifactLifecycleJournalRecordV2;
pub use lifecycle_journal::ArtifactLifecycleJournalSnapshotV2;
pub use lifecycle_journal::ArtifactLifecycleJournalV2;
pub use lifecycle_journal::LifecycleActorEvidenceV2;
pub use lifecycle_journal::LifecycleActorRoleV2;
pub use lifecycle_journal::LifecycleAppendDispositionV2;
pub use limits::MAX_DURABLE_ARTIFACT_RECORDS;
pub use memory_read::DURABLE_MEMORY_READ_STATE_OWNER_SCHEMA_V1;
pub use memory_read::DurableMemoryReadStateOwnerErrorV1;
pub use memory_read::DurableMemoryReadStateOwnerV1;
pub use memory_read::MEMORY_READ_ARTIFACT_SCHEMA_V1;
pub use memory_read::MEMORY_READ_EVALUATION_SCHEMA_V1;
pub use memory_read::MEMORY_READ_STEP_SCHEMA_V1;
pub use memory_read::MemoryReadArtifactOwnerV1;
pub use memory_read::MemoryReadArtifactReceiptV1;
pub use memory_read::MemoryReadArtifactV1;
pub use memory_read::MemoryReadEvaluationOwnerV1;
pub use memory_read::MemoryReadEvaluationReceiptV1;
pub use memory_read::MemoryReadExecutionV1;
pub use memory_read::MemoryReadOwnerErrorV1;
pub use memory_read::MemoryReadStepReceiptV1;
pub use memory_read_cas::MemoryReadBundleMaterializationV1;
pub use memory_read_cas::MemoryReadBundleOwnerErrorV1;
pub use memory_read_cas::MemoryReadBundleReloadV1;
pub use memory_read_qualification::MEMORY_READ_QUALIFICATION_OWNER_SCHEMA_V1;
pub use memory_read_qualification::MemoryReadQualificationExecutionV1;
pub use memory_read_qualification::MemoryReadQualificationExecutorErrorV1;
pub use memory_read_qualification::MemoryReadQualificationOwnerErrorV1;
pub use memory_read_qualification::MemoryReadQualificationOwnerV1;
pub use memory_read_qualification::MemoryReadQualificationStepExecutorV1;
pub use model::ArtifactEvent;
pub use model::ArtifactKind;
pub use model::ArtifactManifest;
pub use model::ArtifactRecord;
pub use model::ArtifactRegistrySnapshot;
pub use model::ArtifactState;
pub use model::LineageDisposition;
pub use model::RegistryAppendDisposition;
pub use model::RegistryAppendReceipt;
pub use model::StateChange;
pub use owner_host::ArtifactOwnerHostError;
pub use owner_host::ArtifactOwnerPublicationCheckpointV1;
pub use owner_host::ArtifactOwnerRecoveryV1;
pub use owner_host::ArtifactOwnerTrustV1;
pub use owner_host::ArtifactOwnerVerifierV1;
pub use owner_host::LearningArtifactOwnerHost;
pub use owner_host::SignedArtifactWriterLeaseV1;
pub use owner_host::SignedCurrentArtifactHeadV1;
pub use owner_host::TrustedArtifactSignerV1;
pub use owner_host::VerifiedCurrentArtifactHeadV1;
pub use owner_service::LearningArtifactOwnerService;
pub use owner_service::LearningArtifactOwnerServiceConfigV1;
pub use owner_service::LearningArtifactOwnerServiceError;
pub use owner_service::LearningArtifactPublishRequestV1;
pub use pinned::LoadedPinnedCandidate;
pub use pinned::PinnedCandidateLoadError;
pub use pinned::PinnedCandidateSpec;
pub use pinned::RevalidatingCandidate;
pub use pinned::VerifiedCurrentRegistryViewV1;
pub use pinned::load_pinned_candidate;
pub use plasticity_owner::PLASTICITY_CANDIDATE_OWNER_SCHEMA_V1;
pub use plasticity_owner::PlasticityCandidateDispositionReceiptV1;
pub use plasticity_owner::PlasticityCandidateMaterializationReceiptV1;
pub use plasticity_owner::PlasticityCandidateOwnerErrorV1;
pub use plasticity_owner::PlasticityCandidateOwnerV1;
pub use plasticity_owner::PlasticityCandidatePhaseV1;
pub use plasticity_owner::PlasticityCandidateRollbackReceiptV1;
pub use production_owner::ArtifactCasOwnerV1;
pub use production_owner::ArtifactLoadReceiptV1;
pub use production_owner::ArtifactWriteReceiptV1;
pub use production_owner::CellDefinitionOwnerV1;
pub use production_owner::CellDefinitionPublicationReceiptV1;
pub use production_owner::CellDefinitionRecordV1;
pub use production_owner::CellDefinitionRegistrySnapshotV1;
pub use production_owner::DefinitionPublicationDispositionV1;
pub use production_owner::ProductionOwnerError;
pub use production_owner::StateCheckpointOwnerV1;
pub use production_owner::StateCheckpointSnapshotV1;
pub use production_owner::StateCommitReceiptV1;
pub use production_owner::StateTombstoneReceiptV1;
pub use publication::ArtifactPublicationError;
pub use publication::ArtifactPublicationIntentV1;
pub use publication::ArtifactPublicationPhaseV1;
pub use publication::ArtifactPublicationReceiptV1;
pub use publication::ArtifactPublicationStatusV1;
pub use publication::ArtifactPublicationTransactionSnapshotV1;
pub use publication::ArtifactPublicationTransactionV1;
pub use qualification_owner::AdapterRoleQualificationExecutorV1;
pub use qualification_owner::PRODUCTION_ROLE_QUALIFICATION_OWNER_SCHEMA_V1;
pub use qualification_owner::ProductionRoleQualificationOwnerErrorV1;
pub use qualification_owner::ProductionRoleQualificationOwnerV1;
pub use qualification_owner::RoleQualificationExecutionV1;
pub use qualification_owner::RoleQualificationExecutorErrorV1;
pub use qualification_owner::RoleQualificationStepExecutorV1;
pub use registry::ArtifactRegistry;
pub use selection::ArtifactSelectionError;
pub use selection::ArtifactSelectionTrustV1;
pub use selection::ArtifactSelectionVerifierV1;
pub use selection::SignedArtifactSelectionV1;
pub use selection::TrustedArtifactSelectorV1;
pub use selection::VerifiedArtifactSelectionV1;
pub use selection::load_selected_candidate;
pub use selection::record_verified_selection;
pub use sensor_core_registry::OperatorSensorCoreEntryV1;
pub use sensor_core_registry::OperatorSensorCoreRegistryV1;
pub use sensor_core_registry::project_operator_sensor_core_registry_v1;
pub use storage::ArtifactStorageError;
pub use storage::CreateOnlyArtifactFile;
pub use storage::RegistryHeadWitnessReceipt;
pub use storage::RegistrySnapshotReceipt;
pub use storage::read_candidate_payload;
pub use storage::read_registry_head_witness;
pub use storage::read_registry_snapshot;
pub use storage::write_candidate_payload;
pub use storage::write_candidate_payload_beneath;
pub use storage::write_registry_head_witness;
pub use storage::write_registry_head_witness_beneath;
pub use storage::write_registry_snapshot;
pub use storage::write_registry_snapshot_beneath;
pub use storage_hygiene::OrphanCleanupDispositionV1;
pub use storage_hygiene::cleanup_zero_length_orphan_beneath;
pub use typed_role::TYPED_ROLE_ARTIFACT_SCHEMA_V1;
pub use typed_role::TYPED_ROLE_EVALUATION_SCHEMA_V1;
pub use typed_role::TYPED_ROLE_STEP_SCHEMA_V1;
pub use typed_role::TypedRoleArtifactEvidenceV1;
pub use typed_role::TypedRoleArtifactOwnerV1;
pub use typed_role::TypedRoleArtifactReceiptV1;
pub use typed_role::TypedRoleArtifactV1;
pub use typed_role::TypedRoleEvaluationOwnerV1;
pub use typed_role::TypedRoleEvaluationReceiptV1;
pub use typed_role::TypedRoleOwnerErrorV1;
pub use typed_role::TypedRoleStepReceiptV1;
pub use typed_role::is_generic_learned_role;
