[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-cognitive-store"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_cognitive_store"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-hepta-types = { path = "../hepta-types" }
codex-hepta-cognitive-types = { path = "../hepta-cognitive-types" }
