#!/usr/bin/env python3
"""Generate channel.matrix status, qualification and review documents."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DOCS = Path("docs/modules/channel.matrix")
GENERATED_HEADER = (
    "<!-- GENERATED by scripts/channel_matrix_docs.py from canonical JSON; "
    "do not edit by hand. -->\n"
)
HEX40 = re.compile(r"[0-9a-f]{40}")
EXPECTED_CLAIMS = (
    "activation",
    "authorityGranted",
    "deploymentQualificationComplete",
    "independentAcceptance",
    "productExecutionProved",
    "productionImplementation",
    "promotion",
    "release",
)
GENERATED_DOCUMENTS = (
    "docs/modules/channel.matrix/CURRENT_STATUS.md",
    "docs/modules/channel.matrix/QUALIFICATION_SUMMARY.md",
    "docs/modules/channel.matrix/REVIEW_GUIDE.md",
)


def load_object(root: Path, relative: str) -> dict[str, Any]:
    def unique(pairs):
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"duplicate JSON key in {relative}: {key}")
            result[key] = value
        return result

    path = root / relative
    if path.is_symlink() or not path.is_file() or path.stat().st_size > 4 * 1024 * 1024:
        raise ValueError(f"invalid canonical document source: {relative}")
    row = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique)
    if not isinstance(row, dict):
        raise ValueError(f"canonical document source must be an object: {relative}")
    return row


def require_sorted_unique(values: object, label: str) -> list[str]:
    if (
        not isinstance(values, list)
        or not values
        or any(not isinstance(value, str) or not value for value in values)
        or values != sorted(values)
        or len(values) != len(set(values))
    ):
        raise ValueError(f"{label} must be a sorted unique non-empty string list")
    return values


def load_model(root_value: Path = ROOT) -> dict[str, Any]:
    root = root_value.resolve(strict=True)
    implementation = load_object(root, f"{DOCS}/IMPLEMENTATION_MAP.json")
    status = load_object(root, f"{DOCS}/MODULE_STATUS.json")
    scenarios = load_object(root, f"{DOCS}/QUALIFICATION_SCENARIOS.json")
    process = load_object(root, f"{DOCS}/PROCESS_FAULT_MATRIX.json")
    production = load_object(root, f"{DOCS}/PRODUCTION_QUALIFICATION_PROFILE.json")
    transport = load_object(root, f"{DOCS}/TRANSPORT_TCB.json")
    review = load_object(root, f"{DOCS}/REVIEW_SLICES.json")
    sources = load_object(root, f"{DOCS}/DOCUMENT_SOURCES.json")

    if (
        implementation.get("schema") != "hepta.module-implementation-map.v3"
        or implementation.get("module") != "channel.matrix"
    ):
        raise ValueError("unsupported implementation map")
    observed = implementation.get("observedAtHead")
    if (
        not isinstance(observed, dict)
        or set(observed) != {"commit", "tree"}
        or any(not isinstance(value, str) or not HEX40.fullmatch(value) for value in observed.values())
    ):
        raise ValueError("implementation map lacks exact frozen source identity")

    if (
        status.get("schema") != "hepta.channel-matrix-module-status.v1"
        or status.get("schemaVersion") != 1
        or status.get("module") != "channel.matrix"
        or status.get("sourceState") != "source_composed_unqualified"
        or status.get("exactCandidateIdentity") != "external_readiness_manifest"
        or status.get("repositoryQualification") != "not_proved"
        or status.get("targetQualification") != "not_proved"
        or status.get("independentAcceptance") != "not_proved"
    ):
        raise ValueError("unsupported module status")
    claims = status.get("claims")
    if (
        not isinstance(claims, dict)
        or tuple(sorted(claims)) != EXPECTED_CLAIMS
        or any(value is not False for value in claims.values())
    ):
        raise ValueError("current module claims must remain an exact closed false set")

    if scenarios.get("schema") != "hepta.channel-matrix-scenarios.v1":
        raise ValueError("unsupported repository scenario registry")
    scenario_rows = scenarios.get("scenarios")
    expected_q = [f"MATRIX-Q{index:02d}" for index in range(1, 30)]
    if (
        not isinstance(scenario_rows, list)
        or [row.get("id") for row in scenario_rows if isinstance(row, dict)] != expected_q
        or len(scenario_rows) != len(expected_q)
    ):
        raise ValueError("repository scenario registry must be exactly MATRIX-Q01-Q29")

    if (
        process.get("schema") != "hepta.channel-matrix-process-fault-profile.v1"
        or process.get("schemaVersion") != 1
        or process.get("storeBackend") != "sqlite_wal_single_writer"
        or process.get("transport") != "matrix_synapse_authenticated"
    ):
        raise ValueError("unsupported process-fault profile")
    process_rows = process.get("scenarios")
    expected_pf = [f"MATRIX-PF{index:02d}" for index in range(1, 19)]
    if (
        not isinstance(process_rows, list)
        or [row.get("id") for row in process_rows if isinstance(row, dict)] != expected_pf
        or len(process_rows) != len(expected_pf)
    ):
        raise ValueError("process-fault profile must be exactly MATRIX-PF01-PF18")

    if (
        production.get("schema")
        != "hepta.channel-matrix-production-qualification-profile.v1"
        or production.get("schemaVersion") != 1
    ):
        raise ValueError("unsupported production qualification profile")
    target = require_sorted_unique(production.get("targetQualification"), "target qualification")
    acceptance = require_sorted_unique(
        production.get("independentAcceptance"), "independent acceptance"
    )
    if "process_fault_matrix" not in target or set(target) & set(acceptance):
        raise ValueError("production profile lacks process qualification or mixes scopes")

    if (
        transport.get("schema") != "hepta.channel-matrix-transport-tcb.v1"
        or transport.get("schemaVersion") != 1
        or not isinstance(transport.get("productionTransport"), dict)
        or transport["productionTransport"].get("type") != "MatrixSdkClient"
    ):
        raise ValueError("unsupported transport TCB")

    if (
        review.get("schema") != "hepta.channel-matrix-review-slices.v1"
        or review.get("schemaVersion") != 1
        or review.get("module") != "channel.matrix"
        or review.get("historyPolicy") != "append_only_review_slices_no_history_rewrite"
        or review.get("rangePolicy") != "derive_first_last_touch_from_exact_base_and_head"
    ):
        raise ValueError("unsupported review-slice registry")
    slices = review.get("slices")
    expected_slice_ids = [
        "01-sdk-final-use",
        "02-durable-store-migrations",
        "03-runtime-recovery",
        "04-transport-adapter-tcb",
        "05-observability-clock",
        "06-qualification-evidence",
        "07-documentation-generated-status",
    ]
    if (
        not isinstance(slices, list)
        or [row.get("id") for row in slices if isinstance(row, dict)] != expected_slice_ids
        or len(slices) != len(expected_slice_ids)
    ):
        raise ValueError("review slices must be the closed ordered seven-slice inventory")
    seen_paths: set[str] = set()
    for row in slices:
        if (
            not isinstance(row, dict)
            or set(row)
            != {"id", "owner", "deputy", "paths", "invariants", "commands"}
            or not isinstance(row["owner"], str)
            or not row["owner"]
            or not isinstance(row["deputy"], str)
            or not row["deputy"]
        ):
            raise ValueError("invalid review slice")
        paths = require_sorted_unique(row["paths"], f"{row['id']} paths")
        require_sorted_unique(row["invariants"], f"{row['id']} invariants")
        commands = row["commands"]
        if (
            not isinstance(commands, list)
            or not commands
            or any(not isinstance(command, str) or not command for command in commands)
            or len(commands) != len(set(commands))
        ):
            raise ValueError(f"{row['id']} commands must be unique and non-empty")
        duplicates = seen_paths & set(paths)
        if duplicates:
            raise ValueError(f"review-slice paths overlap exactly: {sorted(duplicates)}")
        seen_paths.update(paths)

    if (
        sources.get("schema") != "hepta.channel-matrix-document-sources.v1"
        or sources.get("schemaVersion") != 1
        or sources.get("module") != "channel.matrix"
        or sources.get("policy")
        != "machine_sources_canonical_generated_markdown_read_only"
        or sources.get("generator") != "scripts/channel_matrix_docs.py"
        or sources.get("handWrittenPurpose")
        != "architecture_rationale_security_operations_recovery_only"
    ):
        raise ValueError("unsupported document-source registry")
    machine_sources = require_sorted_unique(sources.get("machineSources"), "machine sources")
    generated = sources.get("generatedDocuments")
    if (
        not isinstance(generated, dict)
        or tuple(sorted(generated)) != GENERATED_DOCUMENTS
        or any(
            not isinstance(value, list)
            or not value
            or value != sorted(value)
            or len(value) != len(set(value))
            for value in generated.values()
        )
    ):
        raise ValueError("generated-document registry is incomplete or unstable")
    for document, inputs in generated.items():
        if document not in GENERATED_DOCUMENTS or any(source not in machine_sources for source in inputs):
            raise ValueError("generated document references a non-canonical source")

    return {
        "implementation": implementation,
        "status": status,
        "scenarios": scenario_rows,
        "process": process_rows,
        "processProfile": process,
        "target": target,
        "acceptance": acceptance,
        "transport": transport,
        "slices": slices,
        "sources": sources,
    }


def state_label(value: str) -> str:
    return value.replace("_", " ")


def render_current_status(model: dict[str, Any]) -> str:
    observed = model["implementation"]["observedAtHead"]
    status = model["status"]
    claims = status["claims"]
    lines = [
        GENERATED_HEADER.rstrip(),
        "# channel.matrix current status",
        "",
        f"Status: **{state_label(status['sourceState'])}**.",
        "",
        "## Canonical identity policy",
        "",
        f"- Frozen ordinary-source commit: `{observed['commit']}`.",
        f"- Frozen ordinary-source tree: `{observed['tree']}`.",
        "- Exact candidate, deterministic merge, GitHub synthetic merge, workflow, run,",
        "  attempt and final merge identities come only from the external readiness manifest.",
        "- A committed Markdown file is never current execution evidence.",
        "",
        "## Evidence state",
        "",
        "| Scope | Canonical state |",
        "|---|---|",
        f"| Repository qualification | `{status['repositoryQualification']}` |",
        f"| Target qualification | `{status['targetQualification']}` |",
        f"| Independent acceptance | `{status['independentAcceptance']}` |",
        f"| Exact candidate identity | `{status['exactCandidateIdentity']}` |",
        "",
        "## Claim boundary",
        "",
        "| Claim | Value |",
        "|---|---:|",
    ]
    for name in EXPECTED_CLAIMS:
        lines.append(f"| `{name}` | `{str(claims[name]).lower()}` |")
    lines.extend(
        [
            "",
            "Missing, queued, canceled, superseded, stale, partial, mixed-attempt or",
            "tampered evidence cannot change any false claim to true. Repository-authored",
            "evidence cannot grant activation, promotion, release or Matrix send authority.",
            "",
            "## Canonical machine sources",
            "",
            "- `MODULE_STATUS.json` owns current claim state.",
            "- `IMPLEMENTATION_MAP.json` owns frozen source and source mappings.",
            "- `scripts/channel_matrix_readiness.py` owns exact candidate/run/attempt joins.",
            "",
        ]
    )
    return "\n".join(lines)


def code_list(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def render_qualification_summary(model: dict[str, Any]) -> str:
    claims = model["status"]["claims"]
    scenario_ids = [row["id"] for row in model["scenarios"]]
    process_ids = [row["id"] for row in model["process"]]
    transport = model["transport"]["productionTransport"]
    lines = [
        GENERATED_HEADER.rstrip(),
        "# channel.matrix qualification summary",
        "",
        "This is a projection of the canonical machine registries. It is not an",
        "execution receipt and grants no authority.",
        "",
        "## Closed inventories",
        "",
        "| Inventory | Scope | Entries |",
        "|---|---|---:|",
        f"| `QUALIFICATION_SCENARIOS.json` | Repository/native scenarios | {len(scenario_ids)} |",
        f"| `PROCESS_FAULT_MATRIX.json` | External process-fault scenarios | {len(process_ids)} |",
        f"| `PRODUCTION_QUALIFICATION_PROFILE.json` | Target checks | {len(model['target'])} |",
        f"| `PRODUCTION_QUALIFICATION_PROFILE.json` | Independent checks | {len(model['acceptance'])} |",
        "",
        f"Repository scenario IDs: {code_list(scenario_ids)}.",
        "",
        f"Process-fault scenario IDs: {code_list(process_ids)}.",
        "",
        "## Runtime qualification boundary",
        "",
        f"- Durable backend: `{model['processProfile']['storeBackend']}`.",
        f"- Target transport: `{model['processProfile']['transport']}`.",
        f"- Registered production transport type: `{transport['type']}`.",
        f"- Registered production transport crate: `{transport['crate']}`.",
        "- PostgreSQL, fake transports and source fixtures cannot satisfy this module's",
        "  target process-fault receipt.",
        "",
        "## Target checks",
        "",
        code_list(model["target"]) + ".",
        "",
        "## Independent acceptance checks",
        "",
        code_list(model["acceptance"]) + ".",
        "",
        "## Current qualification claims",
        "",
    ]
    for name in EXPECTED_CLAIMS:
        lines.append(f"- `{name} = {str(claims[name]).lower()}`")
    lines.append("")
    return "\n".join(lines)


def render_review_guide(model: dict[str, Any]) -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# channel.matrix review guide",
        "",
        "The branch history is append-only. Reviewability is restored with seven closed",
        "path/invariant slices; no force-push or historical rewrite is required.",
        "",
        "For an exact base and head, reviewers derive the first and last touching commit",
        "with `git log --reverse <base>..<head> -- <slice paths>`, then retain the",
        "candidate tree, changed-path list and command receipts as the slice invariant",
        "receipt.",
        "",
    ]
    for row in model["slices"]:
        lines.extend(
            [
                f"## {row['id']}",
                "",
                f"Owner: `{row['owner']}`; deputy: `{row['deputy']}`.",
                "",
                "Paths:",
                "",
            ]
        )
        lines.extend(f"- `{path}`" for path in row["paths"])
        lines.extend(["", "Invariants:", ""])
        lines.extend(f"- `{value}`" for value in row["invariants"])
        lines.extend(["", "Verification:", ""])
        lines.extend(f"- `{command}`" for command in row["commands"])
        lines.append("")
    lines.extend(
        [
            "A green slice receipt is narrower than module readiness. All seven slices, the",
            "single readiness manifest, external target qualification and independent",
            "acceptance remain separate gates.",
            "",
        ]
    )
    return "\n".join(lines)


def render_documents(root_value: Path = ROOT) -> dict[str, str]:
    model = load_model(root_value)
    return {
        "docs/modules/channel.matrix/CURRENT_STATUS.md": render_current_status(model),
        "docs/modules/channel.matrix/QUALIFICATION_SUMMARY.md": render_qualification_summary(model),
        "docs/modules/channel.matrix/REVIEW_GUIDE.md": render_review_guide(model),
    }


def write_documents(root: Path, documents: dict[str, str]) -> None:
    for relative, content in documents.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_documents(root: Path, documents: dict[str, str]) -> list[str]:
    mismatches = []
    for relative, expected in documents.items():
        path = root / relative
        if path.is_symlink() or not path.is_file() or path.read_text(encoding="utf-8") != expected:
            mismatches.append(relative)
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    try:
        root = args.root.resolve(strict=True)
        documents = render_documents(root)
        if args.write:
            write_documents(root, documents)
            return 0
        mismatches = check_documents(root, documents)
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
        parser.exit(1, f"FAIL_CHANNEL_MATRIX_DOCUMENTS: {exc}\n")
    if mismatches:
        print(
            "FAIL_CHANNEL_MATRIX_DOCUMENTS: generated files drifted: "
            + ", ".join(mismatches),
            file=sys.stderr,
        )
        return 1
    print("PASS_CHANNEL_MATRIX_DOCUMENTS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
