#!/usr/bin/env python3
"""One-shot documentation/status corrections for product closure."""

from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    if old in text:
        text = text.replace(old, new, 1)
    elif new not in text:
        raise SystemExit(f"rewrite target drifted: {path}")
    path.write_text(text, encoding="utf-8")


status = Path("scripts/hepta-intelligence-control-status.py")
replace_once(
    status,
    '            "sourceImplementation": all(facts.values()),',
    '''            "sourceImplementation": all(
                value
                for name, value in facts.items()
                if name != "defaultBinaryCanonicalProfileComposed"
            ),''',
)

technical = Path("docs/modules/intelligence.control/TECHNICAL.md")
technical_marker = "## 18. Product-closure source amendment"
technical_text = technical.read_text(encoding="utf-8")
if technical_marker not in technical_text:
    technical_text += '''

## 18. Product-closure source amendment

The exact generation/fence, host-owned provider, formal product-learning,
outbox/restart, canonical invariant, worker-isolation and telemetry contracts
are specified in [`PRODUCT_CLOSURE.md`](PRODUCT_CLOSURE.md). The stable tracked
`IMPLEMENTATION_MAP.json` and `TEST_TRACEABILITY.json` are generated by
`scripts/hepta-intelligence-control-status.py`; CI emits exact-head variants only
after executing the candidate and binds their commit to checkout `HEAD`.

This amendment changes the source claim from “runner present” to the following
separate facts: a concrete host-owned provider and atomic profile API exist; the
prepared run inherits the durable RunStart identity; bound admission rechecks
composition identity; formal Decision/Outcome writes use `LedgerWriter` behind
a durable operations outbox; and observability/hard-timeout policy are source
implemented. The ordinary CLI still lacks an authorized seven-owner factory and
therefore does not compose or advertise canonical intelligence by default.
Real-process provider/App Server E2E, target-host qualification, independent
acceptance, activation and release remain false until their exact receipts are
available.
'''
    technical.write_text(technical_text, encoding="utf-8")

dossier = Path("qualification/module-execution-dossiers/detail/intelligence.control.md")
dossier_marker = "## 9. Product-closure amendment"
dossier_text = dossier.read_text(encoding="utf-8")
if dossier_marker not in dossier_text:
    dossier_text += '''

## 9. Product-closure amendment

The current source candidate adds one RunStart-derived physical identity, one
fence constructor, composition-bound admission, a concrete host-owned invocation
provider, an atomic runner/provider profile API, canonical selected-candidate
membership checks, formal `LedgerWriter` Decision/Outcome APIs, a durable
`kernel.operations` outbox with exact restart replay, physical-terminal Outcome
binding, bounded telemetry and an opt-in hard-timeout Agentd process fence.

These source facts supersede earlier statements that durable product learning
or a provider implementation was wholly absent. They do not prove that the
ordinary CLI composes a provider, that a live provider/App Server path has been
exercised, or that target-host, independent-acceptance, activation, promotion or
release gates are closed. Exact status and test classification come from the
generated module JSON and its CI exact-head artifacts.
'''
    dossier.write_text(dossier_text, encoding="utf-8")
