#!/usr/bin/env python3
"""Verify the all-module execution-dossier documentation companion."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DOSSIER_PATH = "qualification/module-execution-dossiers/MODULE_DOSSIERS.json"
README_PATH = "qualification/module-execution-dossiers/README.md"
TECHNICAL_PATH = "qualification/module-execution-dossiers/TECHNICAL.md"
STATUS_PATH = "qualification/module-execution-dossiers/STATUS.md"
MODULES_PATH = "docs/modules/MODULES.json"
MODULE_DOCS_PATH = "docs/modules/MODULE_DOCS.json"
SOURCE_BINDINGS_PATH = "docs/modules/SOURCE_BINDINGS.json"
READINESS_PATH = "docs/readiness/READINESS.json"
STATUS_MODEL_PATH = "docs/readiness/STATUS_MODEL.json"
READINESS_GAPS_PATH = "docs/readiness/GAPS.json"
CNS_PATH = "docs/cns/CNS_ARCHITECTURE.json"
PARALLEL_PATH = "docs/readiness/PARALLEL_DEVELOPMENT.md"
READINESS_README_PATH = "docs/readiness/README.md"
HANDOFF_PATH = "tools/hepta-engineering-control/INTEGRATION_HANDOFF.md"
WORKFLOW_PATH = ".github/workflows/hepta-implementation-readiness.yml"

PLAN_ID = "HEPTA-GLOBAL-MODULAR-DEVELOPMENT-PLAN"
PLAN_VERSION = "8.0.0"
OVERLAY_ID = "HEPTA-V8-PRECODING-READINESS"
OVERLAY_VERSION = "8.2.0-readiness"
GAP_IDS = [f"IMPL-DOC-{index:03d}" for index in range(1, 13)]
EXTERNAL_IDS = [f"RDY-EXT-{index:03d}" for index in range(1, 10)]
FAULT_IDS = [
    "FP-CONTRACT",
    "FP-DURABLE-OWNER",
    "FP-RUNTIME",
    "FP-EFFECT-BOUNDARY",
    "FP-LEARNING-OFFLINE",
    "FP-UI",
    "FP-ENGINEERING-ASSIMILATION",
]
PERFORMANCE_IDS = [
    "PERF-LIBRARY",
    "PERF-DURABLE",
    "PERF-HOT-LOCAL",
    "PERF-CONTROL",
    "PERF-ADAPTER",
    "PERF-OFFLINE",
    "PERF-UI",
    "PERF-ENGINEERING",
]
PROFILE_FIELDS = [
    "runtimeClass",
    "stateClass",
    "faultProfile",
    "performanceProfile",
    "nduParticipation",
    "assimilationComponents",
    "externalGateIds",
]
AUTHORITY_KEYS = [
    "runtimeAuthority",
    "productionCaller",
    "productionWriter",
    "modelInvocation",
    "providerDispatch",
    "toolExecution",
    "networkConnect",
    "externalFilesystemMutation",
    "secretOperation",
    "matrixSend",
    "externalEffect",
    "fleetMutation",
    "canonicalSelection",
    "merge",
    "operatorAcceptance",
    "promotion",
    "release",
]
RECEIPT_FIELDS = [
    "sourceReceipt",
    "moduleGuideDigest",
    "declaredSourceRoots",
    "entrypoints",
    "consumerCallsites",
    "hostRuntimeIdentity",
    "binaryOrArtifactDigest",
    "configurationAndBodyGeneration",
    "ownedPhysicalState",
    "schemaAndMigration",
    "singleWriterFence",
    "terminalObserver",
    "revocationSource",
    "faultResults",
    "resourceMeasurements",
    "fallback",
    "rollbackPredecessor",
    "externalGateDisposition",
]


class DuplicateKey(ValueError):
    pass


def pairs(items: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in items:
        if key in result:
            raise DuplicateKey(key)
        result[key] = value
    return result


def die(message: str) -> None:
    raise SystemExit("FAIL_HEPTA_MODULE_EXECUTION_DOSSIERS: " + message)


def need(condition: bool, message: str) -> None:
    if not condition:
        die(message)


def load(path: str) -> dict[str, Any]:
    try:
        return json.loads(
            (ROOT / path).read_text(encoding="utf-8"), object_pairs_hook=pairs
        )
    except Exception as exc:
        die(f"{path}: {exc}")


def status_text(
    dossier: dict[str, Any], readiness: dict[str, Any], cns: dict[str, Any]
) -> str:
    return "\n".join(
        [
            "# Hepta Module Execution Dossier Status",
            "",
            "> Generated by `python3 scripts/hepta-implementation-dossiers.py generate-status`. Do not edit by hand.",
            "",
            f"**Parent plan:** `{PLAN_ID}` v{PLAN_VERSION}  ",
            f"**Readiness overlay:** `{OVERLAY_ID}` v{OVERLAY_VERSION}  ",
            "**Canonical qualification status:** `specification_closed=closed`; `implementation_closed=open`; `external_evidence_closed=open`",
            "Status vocabulary: [`docs/readiness/STATUS_MODEL.json`](../../docs/readiness/STATUS_MODEL.json).",
            "",
            "## Closed execution-document surface",
            "",
            f"- Registered modules with execution dossiers: **{len(dossier['moduleProfiles'])}**",
            f"- Primary implementation lanes: **{len(readiness['implementationLanes'])}**",
            f"- CNS organ roles projected into module dossiers: **{len(cns['organs'])}**",
            f"- Module receipt fields: **{len(dossier['moduleReceiptFields'])}**",
            f"- Mandatory fault profiles: **{len(dossier['faultProfileIds'])}**",
            f"- Performance measurement profiles: **{len(dossier['performanceProfileIds'])}**",
            f"- Additional documentation-depth gaps closed: **{len(dossier['documentationGapClosures'])}**",
            f"- External capability/evidence gates retained: **{len(dossier['externalGateIds'])}**",
            "- Positive authority flags: **0**",
            "",
            "The dossier closes ambiguity about entrypoints, callers, host identity, physical state, migrations, single writers, terminal observers, fault suites, target-host measurements, NDU participation, organ mapping, self-iteration and external-system assimilation. Its canonical projection is specification_closed only; it does not claim that any missing runtime, hardware, future-window, independent-review, canary, selection, promotion or release evidence exists.",
            "",
        ]
    )


def inverse_cns_organs(
    cns: dict[str, Any], module_ids: set[str]
) -> dict[str, list[str]]:
    projection: dict[str, list[str]] = {module_id: [] for module_id in module_ids}
    for organ in cns["organs"]:
        for module_id in organ["moduleBindings"]:
            if module_id in projection:
                projection[module_id].append(organ["id"])
    for module_id in projection:
        projection[module_id].sort()
    return projection


def verify() -> int:
    dossier = load(DOSSIER_PATH)
    modules = load(MODULES_PATH)["modules"]
    module_docs = load(MODULE_DOCS_PATH)["modules"]
    source_bindings = load(SOURCE_BINDINGS_PATH)["bindings"]
    readiness = load(READINESS_PATH)
    status_model = load(STATUS_MODEL_PATH)
    readiness_gaps = load(READINESS_GAPS_PATH)
    cns = load(CNS_PATH)
    need(
        status_model.get("schema") == "hepta.qualification-readiness-status.v1"
        and status_model.get("schemaVersion") == 1,
        "canonical status model",
    )
    dossier_projection = status_model.get("projection", {}).get("execution_dossiers", {})
    need(
        dossier_projection.get("specification_closed") == "closed"
        and dossier_projection.get("implementation_closed") == "open"
        and dossier_projection.get("external_evidence_closed") == "open",
        "dossier status projection",
    )

    need(
        dossier.get("schema") == "hepta.module-execution-dossier.v1"
        and dossier.get("schemaVersion") == 1,
        "dossier schema",
    )
    need(
        dossier.get("documentClass") == "qualification_companion"
        and dossier.get("authorityScope")
        == "module_execution_documentation_depth_only",
        "dossier class",
    )
    need(
        dossier.get("planId") == PLAN_ID
        and dossier.get("planVersion") == PLAN_VERSION
        and dossier.get("readinessOverlayId") == OVERLAY_ID
        and dossier.get("readinessOverlayVersion") == OVERLAY_VERSION,
        "plan and overlay binding",
    )
    claims = dossier.get("claimBoundary", {})
    need(claims.get("documentationDepthClosed") is True, "documentation depth")
    for key in [
        "sourceImplementation",
        "runtimeComposition",
        "independentAcceptance",
        "longitudinalEfficacy",
        "functionalBiomimicry",
        "physicalSafety",
        "autonomousPropagation",
        "productionRelease",
    ]:
        need(claims.get(key) is False, "positive claim boundary " + key)
    rules = dossier.get("rules", {})
    for key in [
        "canonicalFactsRemainInExistingRegistries",
        "moduleRecordMayNotMintAuthority",
        "emptyDeploymentBindingBlocksActivation",
        "noneByDesignRequiresEvidence",
        "allRuntimeFactsRequireExactCandidateReceipts",
        "allExternalGatesRemainNonSelfCertifiable",
        "onePrimaryLanePerModule",
        "organRolesDerivedFromCnsRegistry",
        "declaredRootsDerivedFromSourceBindings",
    ]:
        need(rules.get(key) is True, "rule " + key)
    need(rules.get("currentRunMutationAllowed") is False, "current-run mutation")
    need(dossier.get("moduleReceiptFields") == RECEIPT_FIELDS, "receipt fields")
    need(dossier.get("faultProfileIds") == FAULT_IDS, "fault profile IDs")
    need(
        dossier.get("performanceProfileIds") == PERFORMANCE_IDS,
        "performance profile IDs",
    )
    need(dossier.get("moduleProfileFields") == PROFILE_FIELDS, "profile fields")

    authority = dossier.get("authorityFlags")
    need(
        isinstance(authority, dict) and list(authority) == AUTHORITY_KEYS,
        "authority key closure/order",
    )
    need(not any(bool(value) for value in authority.values()), "positive authority")

    module_ids = [row["id"] for row in modules]
    need(len(module_ids) == len(set(module_ids)) == 40, "canonical module closure")
    module_set = set(module_ids)
    module_doc_map = {row["module"]: row for row in module_docs}
    source_map = {row["module"]: row for row in source_bindings}
    need(set(module_doc_map) == module_set, "module guide coverage")
    need(set(source_map) == module_set, "source binding coverage")
    for module_id, binding in source_map.items():
        need(binding["declaredRoots"], "empty declared roots " + module_id)

    lane_by_module: dict[str, str] = {}
    for lane in readiness["implementationLanes"]:
        for module_id in lane["modules"]:
            need(module_id not in lane_by_module, "duplicate lane module " + module_id)
            lane_by_module[module_id] = lane["id"]
    need(set(lane_by_module) == module_set, "lane module closure")
    readiness_binding = {
        row["module"]: row["primaryLane"] for row in readiness["moduleBindings"]
    }
    need(readiness_binding == lane_by_module, "readiness lane projection")

    organ_projection = inverse_cns_organs(cns, module_set)
    need(all(organ_projection[module_id] for module_id in module_ids), "organ coverage")

    canonical_external = readiness_gaps["externalCapabilityGates"]
    need([row["id"] for row in canonical_external] == EXTERNAL_IDS, "external order")
    need(dossier.get("externalGateIds") == EXTERNAL_IDS, "external projection")
    need(
        all(
            row["repositoryDocumentationMaySelfCertify"] is False
            for row in canonical_external
        ),
        "self-certifiable external gate",
    )

    profiles = dossier.get("moduleProfiles")
    need(isinstance(profiles, dict), "module profile object")
    need(list(profiles) == module_ids, "module profile order/coverage")
    for module_id, values in profiles.items():
        need(isinstance(values, list) and len(values) == len(PROFILE_FIELDS), module_id)
        row = dict(zip(PROFILE_FIELDS, values, strict=True))
        for key in ["runtimeClass", "stateClass", "nduParticipation"]:
            need(
                isinstance(row[key], str) and len(row[key]) >= 6, module_id + " " + key
            )
        need(row["faultProfile"] in FAULT_IDS, module_id + " fault profile")
        need(
            row["performanceProfile"] in PERFORMANCE_IDS,
            module_id + " performance profile",
        )
        need(
            isinstance(row["assimilationComponents"], list), module_id + " assimilation"
        )
        need(
            isinstance(row["externalGateIds"], list)
            and row["externalGateIds"]
            and set(row["externalGateIds"]) <= set(EXTERNAL_IDS),
            module_id + " external gates",
        )
        guide = (ROOT / module_doc_map[module_id]["path"]).read_text(encoding="utf-8")
        need(
            "## 16. V8.2 pre-coding implementation-readiness overlay" in guide
            and "PARALLEL_DEVELOPMENT.md" in guide,
            module_id + " guide execution overlay",
        )

    gap_rows = dossier.get("documentationGapClosures", [])
    need([row["id"] for row in gap_rows] == GAP_IDS, "gap closure order")
    for row in gap_rows:
        need(list(row) == ["id", "gap", "state", "evidence"], row["id"] + " shape")
        need(
            row["state"] == "closed_specification"
            and isinstance(row["gap"], str)
            and len(row["gap"]) >= 12
            and row["evidence"],
            row["id"] + " closure",
        )
        for evidence_path in row["evidence"]:
            need(
                (ROOT / evidence_path).is_file(),
                row["id"] + " evidence " + evidence_path,
            )

    parallel = (ROOT / PARALLEL_PATH).read_text(encoding="utf-8")
    handoff = (ROOT / HANDOFF_PATH).read_text(encoding="utf-8")
    readiness_readme = (ROOT / READINESS_README_PATH).read_text(encoding="utf-8")
    dossier_readme = (ROOT / README_PATH).read_text(encoding="utf-8")
    technical = (ROOT / TECHNICAL_PATH).read_text(encoding="utf-8")
    workflow = (ROOT / WORKFLOW_PATH).read_text(encoding="utf-8")
    combined = "\n".join(
        [parallel, handoff, readiness_readme, dossier_readme, technical]
    )
    need(
        DOSSIER_PATH in parallel
        and DOSSIER_PATH in handoff
        and DOSSIER_PATH in readiness_readme
        and TECHNICAL_PATH in parallel
        and TECHNICAL_PATH in readiness_readme,
        "dossier discovery links",
    )
    for module_id in module_ids:
        need(module_id in parallel, "parallel matrix missing " + module_id)
    for gap_id in GAP_IDS:
        need(gap_id in parallel, "parallel gap missing " + gap_id)
        need(gap_id in technical, "technical gap missing " + gap_id)
    for profile_id in FAULT_IDS + PERFORMANCE_IDS:
        need(profile_id in parallel, "parallel profile missing " + profile_id)
    for field in RECEIPT_FIELDS:
        need(field in handoff, "handoff field missing " + field)
        need(field in technical, "technical field missing " + field)
    need(len(technical.encode("utf-8")) >= 12000, "technical document too small")
    need(
        len(re.findall(r"\b[\w.-]+\b", technical)) >= 1800,
        "technical document too short",
    )
    for section in [
        "## 1. Scope and truth boundary",
        "## 2. Module execution receipt contract",
        "## 3. Entrypoints, callers and runtime composition",
        "## 4. Physical state, schema and single-writer semantics",
        "## 5. Fault, recovery and fallback profiles",
        "## 6. Performance and resource measurement",
        "## 7. CNS organ mapping and multi-timescale control",
        "## 8. NDU participation and non-applicability",
        "## 9. Longitudinal learning closed loop",
        "## 10. Governed module self-iteration",
        "## 11. Generic external-system assimilation",
        "## 12. Embodied implementation requirements",
        "## 13. Parallel delivery and integration waves",
        "## 14. Documentation-depth gap closure",
        "## 15. External capability gates",
        "## 16. Coding and activation checklist",
    ]:
        need(section in technical, "technical section " + section)

    for command in [
        "python3 scripts/hepta-implementation-dossiers.py self-test",
        "python3 scripts/hepta-implementation-dossiers.py generate-status --check",
        "python3 scripts/hepta-implementation-dossiers.py verify",
    ]:
        need(workflow.count(command) == 2, "workflow coverage " + command)
    need(
        not re.search(r"\b(?:TODO|TBD|FIXME|XXX)\b", combined, re.I),
        "unresolved marker in dossier documentation",
    )
    need(
        (ROOT / STATUS_PATH).read_text(encoding="utf-8")
        == status_text(dossier, readiness, cns),
        "dossier status stale",
    )

    print(
        json.dumps(
            {
                "status": "PASS_HEPTA_MODULE_EXECUTION_DOSSIERS",
                "modules": len(profiles),
                "lanes": len(readiness["implementationLanes"]),
                "organs": len(cns["organs"]),
                "receiptFields": len(RECEIPT_FIELDS),
                "faultProfiles": len(FAULT_IDS),
                "performanceProfiles": len(PERFORMANCE_IDS),
                "documentationGapsClosed": len(gap_rows),
                "externalGatesRetained": len(EXTERNAL_IDS),
                "authorityGranted": False,
                "runtimeCompositionClaimed": False,
            },
            sort_keys=True,
        )
    )
    return 0


def generate_status(check: bool) -> int:
    status_model = load(STATUS_MODEL_PATH)
    need(status_model.get("schema") == "hepta.qualification-readiness-status.v1", "canonical status model")
    text = status_text(load(DOSSIER_PATH), load(READINESS_PATH), load(CNS_PATH))
    path = ROOT / STATUS_PATH
    if check:
        need(
            path.is_file() and path.read_text(encoding="utf-8") == text, "status stale"
        )
        print("PASS_HEPTA_MODULE_EXECUTION_DOSSIER_STATUS")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print("WROTE " + STATUS_PATH)
    return 0


def self_test() -> int:
    try:
        json.loads('{"a":1,"a":2}', object_pairs_hook=pairs)
        die("duplicate key accepted")
    except DuplicateKey:
        pass
    fixture = {
        "organs": [
            {"id": "o2", "moduleBindings": ["m1"]},
            {"id": "o1", "moduleBindings": ["m1", "outside"]},
        ]
    }
    need(
        inverse_cns_organs(fixture, {"m1"}) == {"m1": ["o1", "o2"]},
        "inverse organ fixture",
    )
    need(len(RECEIPT_FIELDS) == len(set(RECEIPT_FIELDS)) == 18, "receipt fixture")
    need(len(FAULT_IDS) == 7 and len(PERFORMANCE_IDS) == 8, "profile fixture")
    print(
        json.dumps(
            {
                "status": "PASS_HEPTA_MODULE_EXECUTION_DOSSIER_SELF_TEST",
                "cases": [
                    "duplicate_key",
                    "inverse_organ_projection",
                    "receipt_fields",
                    "profile_ids",
                ],
                "authorityGranted": False,
            },
            sort_keys=True,
        )
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("verify")
    sub.add_parser("self-test")
    status = sub.add_parser("generate-status")
    status.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.command == "verify":
        return verify()
    if args.command == "self-test":
        return self_test()
    return generate_status(args.check)


if __name__ == "__main__":
    sys.exit(main())
