#!/usr/bin/env python3
"""Fail-closed G14 synchronization after all knowledge.graph source transforms."""
from __future__ import annotations

import hashlib
from pathlib import Path
from typing import NoReturn

ROOT = Path(__file__).resolve().parents[1]

# Each rule names one exact post-transform paragraph or line by a unique prefix and
# SHA-256. This keeps transform ordering explicit without embedding a second copy
# of the superseded prose.
RULES: tuple[tuple[str, str, str, str, str], ...] = (
    ('docs/modules/knowledge.graph/TECHNICAL.md', 'paragraph', 'The cognitive knowledge-', 'cdc327039141890d794c05722e91ef23c36131e52bfebd56b0c205d389145ae9', 'The cognitive knowledge-graph product integration is cross-owner evidence rather than a second module root. `codex-rs/hepta-memory/src/cognitive_kg_store.rs` is the canonical cognitive-facts adapter and SQLite publication owner integration; `codex-rs/hepta-memory/src/cognitive_retrieval.rs` is the product read adapter. Migration `0013_kg_generation_semantics.sql` persists canonical generation/publication receipts, while G14 migration `0014_kg_incremental_generation_storage.sql` keeps immutable revision facts canonical, stores compact generation/source-cut witnesses, and demotes legacy per-generation physical rows to compatibility shells. These adapters call `hepta-kg` V2 semantics instead of duplicating a second graph policy.'),
    ('docs/modules/knowledge.graph/TECHNICAL.md', 'paragraph', 'For the cognitive knowledge projection, t', '6f475e8a66143e7155d087f3fb3788e5c075649fe38564b1a75d37666dfdffdb', 'For the cognitive knowledge projection, the existing `cognitive_1.sqlite3` owner remains the only durable store. Since migration `0014_kg_incremental_generation_storage.sql`, a new generation does **not** copy a complete `kg_nodes`/`kg_edges` snapshot. Immutable revision-scoped entity and relation facts remain the physical content owner. Generation 1 is built completely; subsequent generations apply the exact predecessor-bound incremental delta, and every 64th generation is independently rebuilt and required to match the incremental canonical bytes before commit. Each transaction appends its trigger/source-cut receipt, canonical semantic/publication receipt and immutable `revision_facts_v1` storage witness before the selected pointer advances. Historical generations are reconstructed from the latest trigger revision for each memory at or before that generation. Reopen reconstructs the selected generation from canonical revision facts and recomputes the physical output, generation and predecessor-bound publication digests. Pre-G14 complete snapshots remain readable legacy history, while legacy generations without a canonical V2 semantic receipt cannot drive digest-bound graph expansion.'),
    ('docs/modules/knowledge.graph/TECHNICAL.md', 'paragraph', 'For the cognitive knowledge projection, `', 'bf4a571cacdf30908ff4cb3647d212aba5c96d2bd27b704e9e1b75c288a4bd9d', 'For the cognitive knowledge projection, `CognitiveStore::refresh_scope_projection_tx` is the durable mutation boundary. One SQLite transaction observes the exact current source cut, derives the canonical V2 generation, reconstructs the exact predecessor, validates `publish_generation`, applies an idempotent incremental physical delta, appends compact G14 generation/semantic/storage receipts and CAS-advances `kg_projection.generation`. Every 64th generation also executes a complete rebuild oracle and requires byte-identical canonical output before commit. The selected pointer therefore cannot name a generation whose canonical receipt and compact-storage witness were not durably inserted first.'),
    ('docs/modules/knowledge.graph/TECHNICAL.md', 'paragraph', 'The kernel exposes both ', '597e044cdd6b61a53fbe70ab3518c4d781c96f0f92fdd96c777c46c8e71337a6', 'The kernel exposes both the compatibility query entry and `ValidatedKnowledgeGenerationV2`. The validated form checks the complete immutable generation once, records the aggregate support budget and builds deterministic bidirectional adjacency indexes. The product GraphOneHop path reconstructs and digest-fences that persisted generation once, wraps it as `ValidatedKnowledgeGenerationV2`, and submits one merged multi-seed query through `hepta_kg::query_validated_relations`. The generation-bound adjacency index scans only the union of candidate edge indexes while preserving canonical order, temporal visibility and exact `omitted_count`; a request/generation-scoped physical support index maps selected support identities back to immutable memory occurrences without repeated SQL scans. Both query forms enforce whole-generation support/byte ceilings plus query seed/relation-kind ceilings, and generation, publication and query digests stream directly into SHA-256 rather than allocating a second complete byte buffer. The legacy unvalidated query remains a compatibility entry point. `apply_incremental_delta` is the selected durable writer algorithm, while periodic complete rebuild is the independent oracle rather than the ordinary mutation path.'),
    ('docs/modules/knowledge.graph/TECHNICAL.md', 'paragraph', 'The [module-specific imp', '4027d170abb5f778c5244c4018d06b294f2828a8cfd43892eabbf5ae7281487a', "The [module-specific implementation design](../../../qualification/module-execution-dossiers/detail/knowledge.graph.md) specifies this module's algorithm and pilot ceilings. The current durable writer applies one bounded, idempotent generation delta for each logical mutation. Generation 1 and every 64th generation also execute a complete rebuild oracle; a mismatch fails the transaction closed. Complete physical source-cut assembly and the reopen digest scan remain explicit scale boundaries. Target-host p95/p99, RSS and DB-growth receipts remain mandatory before production qualification."),
    ('docs/modules/knowledge.graph/TECHNICAL.md', 'line', '- [codex-rs/hepta-memory/m', 'd293024fca6433d4459773a85c9ee3a67199feff07ecd7ceadcb3bc0a5d0422f', '- [codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql](../../../codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql) for immutable semantic receipts and current-generation fencing.\n- [codex-rs/hepta-memory/migrations/0014_kg_incremental_generation_storage.sql](../../../codex-rs/hepta-memory/migrations/0014_kg_incremental_generation_storage.sql) for G14 compact generation/source-cut storage, revision-fact reconstruction, and legacy physical compatibility shells.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'paragraph', 'The repository PERF-LIBR', '3c108c2322b0337021af3f9ce89b4a8e085d47aca5d24b364fe2dd2053df299b', 'The repository PERF-LIBRARY probe drives 256 real product mutations to 4,096 physical nodes and 32,768 physical edges, then samples product retrieval/GraphOneHop and ordinary reopen while reporting p50/p95/p99, throughput, DB/WAL size, RSS and Linux CPU ticks. The kernel also emits a canonical-cardinality/high-fanout JSON receipt with its raw log retained as an artifact. These shared-runner receipts are measurements, not target-host admission. The selected writer is incremental after generation 1, and every 64th generation executes a complete rebuild oracle whose canonical bytes must match before commit.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'line', '- **Canonical determinis', '895f6b7da7c6861bc0487b66753ac80103f304a42282902bc7d114e08e882b7e', '- **Canonical deterministic core:** `build_complete_generation`, `apply_incremental_delta`, `publish_generation`, `ValidatedKnowledgeGenerationV2` and validated relation-query entry points are implemented in [codex-rs/hepta-kg/src/generation.rs](../../../codex-rs/hepta-kg/src/generation.rs). V2 preserves canonical/custom relation identity, explicit support lineage, validity windows, exact predecessor publication and generation-bound queries. Generation digesting is streaming rather than assembling one unbounded canonical byte vector. Whole-generation support count, canonical input bytes, query seed count and relation-kind count are independently bounded. Query results bind a canonical request digest covering exact seeds, relation filters, temporal cut and edge bound, so a result receipt cannot be replayed as evidence for a different request that happens to return the same edges.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'line', '- **Cognitive source ada', '27d61d6135f4dbb689af9ae870454a253af2796eb5fe3153b4105a6e713454a6', '- **Cognitive source adapter and durable owner:** [codex-rs/hepta-memory/src/cognitive_kg_store.rs](../../../codex-rs/hepta-memory/src/cognitive_kg_store.rs) derives V2 nodes/edges/supports from existing cognitive SQLite revision facts. `refresh_scope_projection_tx` builds generation 1 completely, applies exact incremental deltas thereafter, reconstructs the predecessor, validates `publish_generation`, persists compact G14 generation metadata plus immutable semantic receipts, and CAS-advances the selected generation inside the same SQLite transaction. Every 64th generation also performs a complete rebuild and requires byte-identical canonical output. It does not create a second fact store.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'line', '- **Persisted semantic i', '52386780859daed48ed74b88db2e16cc52e1d23bd45a8af4b6ac3867b610c27b', '- **Persisted semantic identity and recovery:** [0013_kg_generation_semantics.sql](../../../codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql) stores source-snapshot, generation-vector, graph-profile, generation and publication digests. G14 [0014_kg_incremental_generation_storage.sql](../../../codex-rs/hepta-memory/migrations/0014_kg_incremental_generation_storage.sql) keeps immutable revision facts canonical, stores compact generation/source-cut witnesses, and converts legacy per-generation node/edge/support tables into compatibility shells. Reopen recomputes physical input/output truth from revision facts, reconstructs canonical V2 semantics, and replays predecessor-bound publication; tampered or partial current receipts fail closed. Legacy pre-0011 history cannot drive digest-bound graph expansion without a V2 receipt.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'line', '- **Product query consum', 'cae314ec542a963cc309ac0b92380d97703424d5a0200899edbaa50438abdf79', '- **Product query consumer:** the GraphOneHop path in [cognitive_retrieval.rs](../../../codex-rs/hepta-memory/src/cognitive_retrieval.rs) reconstructs and digest-fences the persisted V2 generation once, wraps it as `ValidatedKnowledgeGenerationV2`, merges all admitted seeds into one generation-bound indexed query, and caches the physical support index for that request/generation. Relation selection, temporal visibility and truncation therefore have one semantic owner; SQL only resolves kernel-selected support identities back to physical memory occurrences.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'line', '- **Current claim bounda', '9287a6c830d1109ed00612ff5de8ccfbacd5e8b4e54c9354216e5f2d80a8680f', '- **Current claim boundary:** the cognitive **read** product caller is composed and this candidate makes scoped cognitive mutation the default Agentd product profile while ordinary Codex remains default-off. The separate `qualification-cognitive-write` feature only adds the qualification turn-witness seam. The prompt.registry → knowledge.graph → prompt.optimizer relation path is source-composed as a separate authority-free projection/consumer chain. The incremental writer, periodic full-rebuild oracle, validated adjacency query and request-scoped physical support cache are source-implemented, but remain pending successful exact-head and deterministic synthetic-merge receipts. Module-wide `productionImplementation` and `productExecutionProved` remain false until those receipts are green; target-host qualification, independent semantic review, operator acceptance, canary and rollback rehearsal remain separate gates.'),
    ('qualification/module-execution-dossiers/detail/knowledge.graph.md', 'paragraph', 'The compatibility bounde', 'ac2fd6458d15595a80b079d4cc690d707ec48505b03b9cf30118b36390f6d5d7', 'The bounded query clones only returned visible supports. `ValidatedKnowledgeGenerationV2` performs full validation once, binds deterministic node/adjacency indexes to that immutable generation, and then scans only the union of candidate edges adjacent to the merged seed set. Exact omission counting still covers the complete matching candidate set. Diagnostic work counters separate validation, candidate scans, support inspection and copies while preserving canonical result bytes. This claims generation-bound indexed lookup and bounded result copying, not constant-time query complexity or unbounded-history elimination.'),
    ('codex-rs/hepta-memory/LANE_C_SQLITE.md', 'paragraph', '`CognitiveStore::lane_c_', '86f1f9c80e0ca7c8368b191618b53d24b71467808899eb9a38c880822e220e85', '`CognitiveStore::lane_c_snapshot` projects the existing `cognitive_1.sqlite3`\ndatabase into `hepta-cognitive-types::CognitiveSnapshot`. Existing memory/source\nwrite APIs remain the only source-fact writers. The knowledge-graph integration\nadds no second database, background synchronization, or replacement source\nidentity format. Migration `0013_kg_generation_semantics.sql` adds immutable\ncanonical generation/publication receipts to this same SQLite owner; G14\n`0014_kg_incremental_generation_storage.sql` stores compact generation/source-cut\nwitnesses, reconstructs history from immutable revision facts, and leaves the\nlegacy per-generation physical tables as compatibility shells. The in-memory\n`hepta-cognitive-store` V2 implementation is not a durability backend.'),
    ('codex-rs/hepta-memory/LANE_C_SQLITE.md', 'paragraph', 'Knowledge-graph material', 'c4bcb446bd0a84d6b1b739c236458338d98d3daf06741c95950d89958fab4060', 'Knowledge-graph materialization in `refresh_scope_projection_tx` derives one canonical\n`hepta-kg` V2 generation from the exact current cognitive source cut, validates its\npredecessor-bound publication, applies an idempotent incremental physical delta,\npersists compact G14 generation metadata and semantic receipts, and only then\nCAS-advances the current generation in the same transaction. Generation 1 and every\n64th generation execute a complete rebuild oracle whose canonical bytes must match.\nGraphOneHop reconstructs and digest-fences that generation once, wraps it as\n`ValidatedKnowledgeGenerationV2`, issues one merged multi-seed adjacency query, and\nuses a request/generation-scoped physical support index; SQLite only maps selected\nsupport identities back to physical memory occurrences.'),
    ('codex-rs/hepta-memory/LANE_C_SQLITE.md', 'paragraph', '`cognitive_kg_oracle_tes', 'cd556412ad17e460bec501ebdb39b73c733681b904571a7a60e6229dc1005987', '`cognitive_kg_oracle_tests.rs` additionally verifies full/incremental canonical V2 equivalence against SQLite, persisted physical/canonical digests, reopen, visibility, correction and tombstone; store tamper cases reject invalid canonical generation/publication receipts. The production writer repeats the complete rebuild oracle every 64 generations and fails the transaction closed on any divergence.'),
)


def fail(message: str) -> NoReturn:
    raise SystemExit(f"FAIL_HEPTA_KG_G14_DOCS_FINALIZE: {message}")


def apply_rule(text: str, rule: tuple[str, str, str, str, str]) -> str:
    path, mode, prefix, expected_sha256, replacement = rule
    units = text.split("\n\n") if mode == "paragraph" else text.splitlines()
    matches = [unit for unit in units if unit.startswith(prefix)]
    if len(matches) != 1:
        fail(f"{path}: expected one exact post-transform G14 {mode}, found {len(matches)} for {prefix!r}")
    selected = matches[0]
    observed = hashlib.sha256(selected.encode("utf-8")).hexdigest()
    if observed != expected_sha256:
        fail(f"{path}: G14 {mode} drift for {prefix!r}: {observed} != {expected_sha256}")
    if text.count(selected) != 1:
        fail(f"{path}: selected G14 {mode} is not unique in source bytes")
    return text.replace(selected, replacement, 1)


def synchronize_documents(root: Path = ROOT) -> tuple[str, ...]:
    touched: list[str] = []
    by_path: dict[str, list[tuple[str, str, str, str, str]]] = {}
    for rule in RULES:
        by_path.setdefault(rule[0], []).append(rule)
    for relative, rules in by_path.items():
        path = root / relative
        source = path.read_text(encoding="utf-8")
        for rule in rules:
            source = apply_rule(source, rule)
        path.write_text(source, encoding="utf-8")
        touched.append(relative)
    return tuple(touched)


def main() -> int:
    touched = synchronize_documents()
    print("G14_DOCS=" + ",".join(touched))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
