#!/usr/bin/env python3
"""Fail-closed G14 documentation synchronization for the materialized KG pipeline."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "docs/modules/knowledge.graph/TECHNICAL.md": [
        (
            "The cognitive knowledge-graph product integration is cross-owner evidence rather than a second module root. `codex-rs/hepta-memory/src/cognitive_kg_store.rs` is the canonical cognitive-facts adapter and SQLite publication owner integration; `codex-rs/hepta-memory/src/cognitive_retrieval.rs` is the product read adapter; migration `0013_kg_generation_semantics.sql` persists the canonical generation/publication receipts. These adapters call `hepta-kg` V2 semantics instead of duplicating a second graph policy.",
            "The cognitive knowledge-graph product integration is cross-owner evidence rather than a second module root. `codex-rs/hepta-memory/src/cognitive_kg_store.rs` is the canonical cognitive-facts adapter and SQLite publication owner integration; `codex-rs/hepta-memory/src/cognitive_retrieval.rs` is the product read adapter. Migration `0013_kg_generation_semantics.sql` persists canonical generation/publication receipts, while G14 migration `0014_kg_incremental_generation_storage.sql` keeps immutable revision facts canonical, stores compact generation/source-cut witnesses, and demotes legacy per-generation physical rows to compatibility shells. These adapters call `hepta-kg` V2 semantics instead of duplicating a second graph policy.",
        ),
        (
            "For the cognitive knowledge projection, the existing `cognitive_1.sqlite3` owner remains the only durable store. The adapter derives canonical `KnowledgeGenerationV2` values from immutable/current cognitive facts, invokes `build_complete_generation`, validates predecessor-bound `publish_generation`, writes physical projection rows plus `kg_projection_generation_semantics`, and only then advances the selected generation in the same SQLite transaction. Reopen recomputes the physical output digest, canonical generation digest and predecessor-bound publication digest. Pre-`0011` legacy generations may remain readable history but cannot drive digest-bound graph expansion without a canonical V2 semantic receipt.",
            "For the cognitive knowledge projection, the existing `cognitive_1.sqlite3` owner remains the only durable store. The adapter derives canonical `KnowledgeGenerationV2` values from immutable/current cognitive revision facts, validates predecessor-bound `publish_generation`, applies the exact generation delta to the selected physical projection, persists compact G14 source-cut/generation metadata plus `kg_projection_generation_semantics`, and only then advances the selected generation in the same SQLite transaction. Generation 1 uses a complete build; subsequent generations use the incremental writer, with every 64th generation independently rebuilt and required to match the incremental canonical bytes before commit. Reopen reconstructs the selected generation from canonical revision facts, then recomputes the physical output digest, canonical generation digest and predecessor-bound publication digest. Pre-`0011` legacy generations may remain readable history but cannot drive digest-bound graph expansion without a canonical V2 semantic receipt.",
        ),
        (
            "For the cognitive knowledge projection, `CognitiveStore::refresh_scope_projection_tx` is the durable mutation boundary. One SQLite transaction observes the exact current source cut, derives the canonical V2 generation, reconstructs the exact predecessor, validates `publish_generation`, persists physical rows and semantic receipts, and CAS-advances `kg_projection.generation`. The selected pointer therefore cannot name a generation whose canonical receipt was not durably inserted first.",
            "For the cognitive knowledge projection, `CognitiveStore::refresh_scope_projection_tx` is the durable mutation boundary. One SQLite transaction observes the exact current source cut, derives the canonical V2 generation, reconstructs the exact predecessor, validates `publish_generation`, applies an idempotent incremental physical delta, persists compact G14 generation metadata and semantic receipts, and CAS-advances `kg_projection.generation`. Every 64th generation also executes a complete rebuild oracle and requires byte-identical canonical output before commit. The selected pointer therefore cannot name a generation whose canonical receipt was not durably inserted first.",
        ),
        (
            "The product GraphOneHop read path loads the persisted generation through `load_canonical_generation_tx`, requires the persisted `generation_sha256` to match the reconstructed V2 digest, and delegates relation selection, temporal visibility and truncation to `hepta_kg::query_relations`. SQL after that point only maps kernel-selected support identities back to their physical memory occurrences. `apply_incremental_delta` is retained as an equivalence oracle/reference path; the current durable product writer deliberately rebuilds the bounded complete generation on each logical mutation.",
            "The product GraphOneHop read path loads the persisted generation through `load_canonical_generation_tx`, requires the persisted `generation_sha256` to match the reconstructed V2 digest, wraps it once as `ValidatedKnowledgeGenerationV2`, and delegates one merged multi-seed relation query to `hepta_kg::query_validated_relations`. The generation-bound adjacency index avoids unrelated-edge scans; a request/generation-scoped physical support index maps kernel-selected support identities back to physical memory occurrences without repeated SQL scans. The legacy unvalidated query remains a compatibility entry point. `apply_incremental_delta` is the selected durable writer algorithm, while periodic complete rebuild is the independent oracle rather than the ordinary mutation path.",
        ),
        (
            "The [module-specific implementation design](../../../qualification/module-execution-dossiers/detail/knowledge.graph.md) specifies this module's algorithm and pilot ceilings. The current durable writer deliberately performs one bounded complete-generation rebuild for each logical mutation; `apply_incremental_delta` remains the independent equivalence/reference path until measurements justify selecting it as the durable runtime algorithm.",
            "The [module-specific implementation design](../../../qualification/module-execution-dossiers/detail/knowledge.graph.md) specifies this module's algorithm and pilot ceilings. The current durable writer applies one bounded, idempotent generation delta for each logical mutation. Generation 1 and every 64th generation also execute a complete rebuild oracle; a mismatch fails the transaction closed. Target-host measurements still govern production admission, but they no longer select between an unimplemented incremental path and a full-rebuild product path.",
        ),
        (
            "- [codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql](../../../codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql) for immutable semantic receipts and current-generation fencing.",
            "- [codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql](../../../codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql) for immutable semantic receipts and current-generation fencing.\n- [codex-rs/hepta-memory/migrations/0014_kg_incremental_generation_storage.sql](../../../codex-rs/hepta-memory/migrations/0014_kg_incremental_generation_storage.sql) for G14 compact generation/source-cut storage, revision-fact reconstruction, and legacy physical compatibility shells.",
        ),
    ],
    "qualification/module-execution-dossiers/detail/knowledge.graph.md": [
        (
            "The repository PERF-LIBRARY probe now drives 256 real product mutations to 4,096 physical nodes and 32,768 physical edges, then samples product retrieval/GraphOneHop and ordinary reopen while reporting p50/p95/p99, throughput, DB/WAL size, RSS and Linux CPU ticks. This is a CI measurement receipt, not a target-host latency threshold. Full-generation rebuild remains the selected runtime writer until a concrete target-host budget justifies promoting the independently checked incremental path.",
            "The repository PERF-LIBRARY probe drives 256 real product mutations to 4,096 physical nodes and 32,768 physical edges, then samples product retrieval/GraphOneHop and ordinary reopen while reporting p50/p95/p99, throughput, DB/WAL size, RSS and Linux CPU ticks. The kernel also emits a canonical-cardinality/high-fanout JSON receipt with its raw log retained as an artifact. These shared-runner receipts are measurements, not target-host admission. The selected writer is incremental after generation 1, and every 64th generation executes a complete rebuild oracle whose canonical bytes must match before commit.",
        ),
        (
            "- **Canonical deterministic core:** `build_complete_generation`, `apply_incremental_delta`, `publish_generation` and `query_relations` are implemented in [codex-rs/hepta-kg/src/generation.rs](../../../codex-rs/hepta-kg/src/generation.rs). V2 preserves canonical/custom relation identity, explicit support lineage, validity windows, exact predecessor publication and generation-bound queries. Query results bind a canonical request digest covering exact seeds, relation filters, temporal cut and edge bound, so a result receipt cannot be replayed as evidence for a different request that happens to return the same edges.",
            "- **Canonical deterministic core:** `build_complete_generation`, `apply_incremental_delta`, `publish_generation`, `ValidatedKnowledgeGenerationV2` and validated relation-query entry points are implemented in [codex-rs/hepta-kg/src/generation.rs](../../../codex-rs/hepta-kg/src/generation.rs). V2 preserves canonical/custom relation identity, explicit support lineage, validity windows, exact predecessor publication and generation-bound queries. Generation digesting is streaming rather than assembling one unbounded canonical byte vector. Whole-generation support count, canonical input bytes, query seed count and relation-kind count are independently bounded. Query results bind a canonical request digest covering exact seeds, relation filters, temporal cut and edge bound, so a result receipt cannot be replayed as evidence for a different request that happens to return the same edges.",
        ),
        (
            "- **Cognitive source adapter and durable owner:** [codex-rs/hepta-memory/src/cognitive_kg_store.rs](../../../codex-rs/hepta-memory/src/cognitive_kg_store.rs) derives V2 nodes/edges/supports from the existing cognitive SQLite facts. `refresh_scope_projection_tx` builds the complete V2 candidate, reconstructs the predecessor, validates `publish_generation`, persists physical projection rows and immutable semantic receipts, and CAS-advances the selected generation inside the same SQLite transaction. It does not create a second fact store.",
            "- **Cognitive source adapter and durable owner:** [codex-rs/hepta-memory/src/cognitive_kg_store.rs](../../../codex-rs/hepta-memory/src/cognitive_kg_store.rs) derives V2 nodes/edges/supports from existing cognitive SQLite revision facts. `refresh_scope_projection_tx` builds generation 1 completely, applies exact incremental deltas thereafter, reconstructs the predecessor, validates `publish_generation`, persists compact G14 generation metadata plus immutable semantic receipts, and CAS-advances the selected generation inside the same SQLite transaction. Every 64th generation also performs a complete rebuild and requires byte-identical canonical output. It does not create a second fact store.",
        ),
        (
            "- **Persisted semantic identity and recovery:** [0013_kg_generation_semantics.sql](../../../codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql) stores source-snapshot, generation-vector, graph-profile, generation and publication digests. Reopen recomputes physical input/output truth, reconstructs canonical V2 semantics, and replays predecessor-bound publication; tampered or partial current receipts fail closed. Legacy pre-0011 history cannot drive digest-bound graph expansion without a V2 receipt.",
            "- **Persisted semantic identity and recovery:** [0013_kg_generation_semantics.sql](../../../codex-rs/hepta-memory/migrations/0013_kg_generation_semantics.sql) stores source-snapshot, generation-vector, graph-profile, generation and publication digests. G14 [0014_kg_incremental_generation_storage.sql](../../../codex-rs/hepta-memory/migrations/0014_kg_incremental_generation_storage.sql) keeps immutable revision facts canonical, stores compact generation/source-cut witnesses, and converts legacy per-generation node/edge/support tables into compatibility shells. Reopen recomputes physical input/output truth from revision facts, reconstructs canonical V2 semantics, and replays predecessor-bound publication; tampered or partial current receipts fail closed. Legacy pre-0011 history cannot drive digest-bound graph expansion without a V2 receipt.",
        ),
        (
            "- **Product query consumer:** the GraphOneHop path in [cognitive_retrieval.rs](../../../codex-rs/hepta-memory/src/cognitive_retrieval.rs) reconstructs the persisted V2 generation, fences it by `generation_sha256`, and calls `hepta_kg::query_relations`. Relation selection, temporal visibility and truncation therefore have one semantic owner; SQL only resolves the selected support identities back to physical memory occurrences.",
            "- **Product query consumer:** the GraphOneHop path in [cognitive_retrieval.rs](../../../codex-rs/hepta-memory/src/cognitive_retrieval.rs) reconstructs and digest-fences the persisted V2 generation once, wraps it as `ValidatedKnowledgeGenerationV2`, merges all admitted seeds into one generation-bound indexed query, and caches the physical support index for that request/generation. Relation selection, temporal visibility and truncation therefore have one semantic owner; SQL only resolves kernel-selected support identities back to physical memory occurrences.",
        ),
        (
            "- **Current claim boundary:** the cognitive **read** product caller is composed and this candidate makes scoped cognitive mutation the default Agentd product profile while ordinary Codex remains default-off. The separate `qualification-cognitive-write` feature only adds the qualification turn-witness seam. The prompt.registry → knowledge.graph → prompt.optimizer relation path is now source-composed as a separate authority-free projection/consumer chain. The candidate writer and prompt-factor chain remain pending current exact-head and deterministic synthetic-merge proof. `apply_incremental_delta` remains an oracle/reference equivalence path rather than the selected runtime writer algorithm. Module-wide `productionImplementation` and `productExecutionProved` remain false until those current execution receipts are green; target-host qualification and independent acceptance remain separate gates.",
            "- **Current claim boundary:** the cognitive **read** product caller is composed and this candidate makes scoped cognitive mutation the default Agentd product profile while ordinary Codex remains default-off. The separate `qualification-cognitive-write` feature only adds the qualification turn-witness seam. The prompt.registry → knowledge.graph → prompt.optimizer relation path is source-composed as a separate authority-free projection/consumer chain. The incremental writer, periodic full-rebuild oracle, validated adjacency query and request-scoped physical support cache are source-implemented, but remain pending successful exact-head and deterministic synthetic-merge receipts. Module-wide `productionImplementation` and `productExecutionProved` remain false until those receipts are green; target-host qualification, independent semantic review, operator acceptance, canary and rollback rehearsal remain separate gates.",
        ),
        (
            "The bounded query clones only the returned visible supports. Its diagnostic\n`query_relations_with_work` entry reports validation-record counts separately\nfrom selection scans and copies, with exactly the same canonical result as the\nordinary entry. The full generation still needs validation and exact omissions\nstill require scanning all matching candidates; this change claims bounded\nresult copying, not constant-time lookup or fully localized writes.",
            "The bounded query clones only returned visible supports. `ValidatedKnowledgeGenerationV2` performs full validation once, binds deterministic node/adjacency indexes to that immutable generation, and then scans only the union of candidate edges adjacent to the merged seed set. Exact omission counting still covers the complete matching candidate set. Diagnostic work counters separate validation, candidate scans, support inspection and copies while preserving canonical result bytes. This claims generation-bound indexed lookup and bounded result copying, not constant-time query complexity or unbounded-history elimination.",
        ),
    ],
    "codex-rs/hepta-memory/LANE_C_SQLITE.md": [
        (
            "adds no second database, background synchronization, or replacement source\nidentity format; migration `0013_kg_generation_semantics.sql` adds immutable\ncanonical generation/publication receipts to this same SQLite owner. The\nin-memory `hepta-cognitive-store` V2 implementation is not a durability backend.",
            "adds no second database, background synchronization, or replacement source\nidentity format. Migration `0013_kg_generation_semantics.sql` adds immutable\ncanonical generation/publication receipts to this same SQLite owner; G14\n`0014_kg_incremental_generation_storage.sql` stores compact generation/source-cut\nwitnesses, reconstructs history from immutable revision facts, and leaves the\nlegacy per-generation physical tables as compatibility shells. The in-memory\n`hepta-cognitive-store` V2 implementation is not a durability backend.",
        ),
        (
            "Knowledge-graph materialization in `refresh_scope_projection_tx` derives one canonical\n`hepta-kg` V2 generation from the exact current cognitive source cut, validates its\npredecessor-bound publication, persists physical rows and semantic receipts, and only\nthen CAS-advances the current generation in the same transaction. GraphOneHop reads\nreconstruct that generation, fence it by the persisted generation digest, and delegate\nrelation selection and temporal visibility to `hepta_kg::query_relations`; SQLite only\nmaps selected support identities back to physical memory occurrences.",
            "Knowledge-graph materialization in `refresh_scope_projection_tx` derives one canonical\n`hepta-kg` V2 generation from the exact current cognitive source cut, validates its\npredecessor-bound publication, applies an idempotent incremental physical delta,\npersists compact G14 generation metadata and semantic receipts, and only then\nCAS-advances the current generation in the same transaction. Generation 1 and every\n64th generation execute a complete rebuild oracle whose canonical bytes must match.\nGraphOneHop reconstructs and digest-fences that generation once, wraps it as\n`ValidatedKnowledgeGenerationV2`, issues one merged multi-seed adjacency query, and\nuses a request/generation-scoped physical support index; SQLite only maps selected\nsupport identities back to physical memory occurrences.",
        ),
        (
            "`cognitive_kg_oracle_tests.rs` additionally verifies full/incremental canonical V2 equivalence against SQLite, persisted physical/canonical digests, reopen, visibility, correction and tombstone; store tamper cases reject invalid canonical generation/publication receipts.",
            "`cognitive_kg_oracle_tests.rs` additionally verifies full/incremental canonical V2 equivalence against SQLite, persisted physical/canonical digests, reopen, visibility, correction and tombstone; store tamper cases reject invalid canonical generation/publication receipts. The production writer repeats the complete rebuild oracle every 64 generations and fails the transaction closed on any divergence.",
        ),
    ],
}


def replace_exact(text: str, old: str, new: str, *, path: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one exact G14 anchor, found {count}: {old[:96]!r}")
    return text.replace(old, new)


def main() -> None:
    changed: list[str] = []
    for relative, replacements in REPLACEMENTS.items():
        path = ROOT / relative
        text = path.read_text(encoding="utf-8")
        for old, new in replacements:
            text = replace_exact(text, old, new, path=relative)
        path.write_text(text, encoding="utf-8")
        changed.append(relative)
    print("G14_DOCS=" + ",".join(changed))


if __name__ == "__main__":
    main()
