#!/usr/bin/env python3
"""Verify the tracked inference.worker status template or emit an exact CI receipt."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
STATUS_PATH = ROOT / "docs/modules/inference.worker/CURRENT_STATUS.json"
SOURCE_PATHS = (
    "codex-rs/hepta-infer-worker-host/Cargo.toml",
    "codex-rs/hepta-infer-worker-host/src/lib.rs",
    "codex-rs/hepta-infer-worker-host/src/profiles.rs",
    "codex-rs/hepta-infer-worker-host/src/local_model.rs",
    "codex-rs/hepta-infer-worker-host/src/local_model_tests.rs",
    "codex-rs/hepta-infer-worker-host/src/native_app_server.rs",
    "codex-rs/hepta-infer-worker-host/src/native_run_control.rs",
    "codex-rs/hepta-infer-worker-host/src/final_use_authorizer.rs",
    "docs/modules/inference.worker/IMPLEMENTATION_MAP.json",
    "docs/modules/inference.worker/TECHNICAL.md",
    "docs/modules/inference.worker/PROFILE_BOUNDARIES.md",
)
REQUIRED_STATUS_FIELDS = (
    "source_head",
    "source_tree",
    "source_blob_digests",
    "last_exact_head_run",
    "last_merge_candidate_run",
    "linux_result",
    "macos_result",
    "lib_test_result",
    "binary_test_result",
    "clippy_result",
    "real_hardware_result",
    "composition_result",
    "independent_acceptance_result",
)


def fail(message: str) -> None:
    raise ValueError(message)


def load_template() -> dict[str, Any]:
    data = json.loads(STATUS_PATH.read_text(encoding="utf-8"))
    if data.get("schema") != "hepta.inference-worker-current-status.v1":
        fail("unexpected CURRENT_STATUS schema")
    if data.get("schema_version") != 1 or data.get("module") != "inference.worker":
        fail("CURRENT_STATUS identity is invalid")
    for field in REQUIRED_STATUS_FIELDS:
        if field not in data:
            fail(f"CURRENT_STATUS is missing {field}")
    return data


def require_profile_truth(data: dict[str, Any]) -> None:
    profiles = data.get("profiles")
    if not isinstance(profiles, dict):
        fail("CURRENT_STATUS profiles must be an object")
    expected = {
        "HostedAppServerWorker": ("production-candidate", True, True),
        "LocalModelWorker": ("experimental-non-production", False, False),
        "LegacyReceiptBoundary": ("validation-only", True, False),
    }
    if set(profiles) != set(expected):
        fail("CURRENT_STATUS profile inventory is not closed-world")
    for name, (maturity, default_export, evidence) in expected.items():
        candidate = profiles[name]
        if candidate.get("maturity") != maturity:
            fail(f"{name} maturity drifted")
        if candidate.get("default_export") is not default_export:
            fail(f"{name} default export drifted")
        if candidate.get("product_execution_evidence_allowed") is not evidence:
            fail(f"{name} evidence ceiling drifted")
    if profiles["LocalModelWorker"].get("feature") != "experimental-local-model":
        fail("LocalModelWorker must remain behind experimental-local-model")


def require_reconciliation_truth(data: dict[str, Any]) -> None:
    expected = {
        "exact_app_server_thread_history": "implemented",
        "missing_history_resolution": "not-implemented",
        "trusted_token_usage_reconciliation": "not-implemented",
        "real_provider_target_host_qualification": "not-complete",
    }
    if data.get("provider_reconciliation") != expected:
        fail("provider reconciliation declaration drifted")


def verify() -> None:
    data = load_template()
    require_profile_truth(data)
    require_reconciliation_truth(data)
    if data.get("source_head") is not None or data.get("source_tree") is not None:
        fail("tracked CURRENT_STATUS must not impersonate an exact execution receipt")
    if data.get("source_blob_digests") != {}:
        fail("tracked CURRENT_STATUS blob map must be generated by CI")

    cargo = (ROOT / "codex-rs/hepta-infer-worker-host/Cargo.toml").read_text(
        encoding="utf-8"
    )
    library = (ROOT / "codex-rs/hepta-infer-worker-host/src/lib.rs").read_text(
        encoding="utf-8"
    )
    local_model = (ROOT / "codex-rs/hepta-infer-worker-host/src/local_model.rs").read_text(
        encoding="utf-8"
    )
    if "experimental-local-model =" not in cargo:
        fail("experimental-local-model feature is missing")
    if '#[cfg(feature = "experimental-local-model")]' not in library:
        fail("LocalModelWorker is not feature gated")
    if "pub mod local_model;" not in library:
        fail("sealed local-model implementation is not exported by its feature")
    if "pub mod model_worker;" in library:
        fail("legacy fake-driver model_worker must not be a product API")
    if "#[cfg(test)]\nmod model_worker;" not in library:
        fail("legacy state-machine tests lost their test-only boundary")
    if "pub mod profiles;" not in library:
        fail("public profile truth module is missing")
    for symbol in (
        "pub struct VerifiedResourceGrant",
        "pub struct VerifiedModelManifest",
        "pub struct AttestedModelHandle",
        "pub struct TrustedDeadline",
        "pub struct ResourceManager",
        "pub trait LocalModelDriver",
    ):
        if symbol not in local_model:
            fail(f"local-model implementation is missing {symbol}")


def git(*args: str) -> str:
    return subprocess.check_output(
        ["git", *args], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
    ).strip()


def exact_blob_map() -> dict[str, str]:
    blobs: dict[str, str] = {}
    for path in SOURCE_PATHS:
        candidate = ROOT / path
        if not candidate.is_file():
            fail(f"status source path is absent: {path}")
        blobs[path] = git("rev-parse", f"HEAD:{path}")
    return blobs


def generate(args: argparse.Namespace) -> None:
    data = load_template()
    require_profile_truth(data)
    require_reconciliation_truth(data)
    data["status_mode"] = "exact-candidate CI receipt"
    data["source_head"] = git("rev-parse", "HEAD")
    data["source_tree"] = git("rev-parse", "HEAD^{tree}")
    data["source_blob_digests"] = exact_blob_map()
    data["last_exact_head_run"] = args.exact_head_run
    data["last_merge_candidate_run"] = args.merge_candidate_run
    for field in (
        "linux_result",
        "macos_result",
        "lib_test_result",
        "binary_test_result",
        "clippy_result",
        "real_hardware_result",
        "composition_result",
        "independent_acceptance_result",
    ):
        data[field] = getattr(args, field)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser()
    commands = root.add_subparsers(dest="command", required=True)
    commands.add_parser("verify")
    emit = commands.add_parser("generate")
    emit.add_argument("--output", required=True)
    emit.add_argument("--exact-head-run", required=True)
    emit.add_argument("--merge-candidate-run")
    for field in (
        "linux-result",
        "macos-result",
        "lib-test-result",
        "binary-test-result",
        "clippy-result",
        "real-hardware-result",
        "composition-result",
        "independent-acceptance-result",
    ):
        emit.add_argument(f"--{field}", required=True)
    return root


def main() -> int:
    args = parser().parse_args()
    try:
        if args.command == "verify":
            verify()
        else:
            generate(args)
    except (OSError, ValueError, subprocess.CalledProcessError, json.JSONDecodeError) as error:
        print(f"inference.worker status error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
