#!/usr/bin/env python3
"""Project control.runtime status without turning source facts into qualification.

--write is explicit documentation preparation. --check and --verify-source are
read-only gates. Historical sourceBase is copied unchanged; exact command-head
receipts are produced separately by the qualification workflow.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import subprocess

MAP = "docs/modules/control.runtime/IMPLEMENTATION_MAP.json"
STATE = "docs/modules/control.runtime/CURRENT_STATE.json"
PRODUCT = "docs/modules/control.runtime/CURRENT_PRODUCT_PATH.md"
CLAIMS = ("productionImplementation", "productExecutionProved", "independentAcceptance", "activation", "release")


def unique_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def encode(value):
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def project(row):
    if row.get("module") != "control.runtime":
        raise ValueError("wrong module identity")
    boundary = row.get("claimBoundary", {})
    if not isinstance(boundary, dict):
        raise ValueError("claim boundary must be an object")
    for identity in (row.get("sourceBase"), row.get("observedAtHead")):
        if not isinstance(identity, dict) or any(
            not isinstance(identity.get(key), str)
            or not re.fullmatch(r"[0-9a-f]{40}", identity[key])
            for key in ("commit", "tree")
        ):
            raise ValueError("source identity requires literal commit and tree")
    for name in CLAIMS:
        for value in (row.get(name, False), boundary.get(name, False)):
            if type(value) is not bool or value:
                raise ValueError(f"source-candidate generator cannot issue {name}")
    components = row.get("componentMaturity")
    if not isinstance(components, dict) or not components:
        raise ValueError("component maturity must be explicit")
    required = {"planner", "organHost", "runtimeRegistry", "embodimentReference", "readOnlyAgentd", "plannerStore"}
    if set(components) != required:
        raise ValueError("component maturity inventory mismatch")
    permitted_qualification = {"not_executed", "pending", "failed", "failed_or_incomplete", "blocked", "required"}
    for item in components.values():
        if not isinstance(item, dict) or any(
            not isinstance(item.get(key), str) or not item[key]
            for key in ("sourceState", "productState", "qualificationState")
        ):
            raise ValueError("invalid component maturity")
        if item["qualificationState"] not in permitted_qualification:
            raise ValueError("source projection cannot issue component qualification")
    objects = row.get("sourceObjects", [])
    if not objects:
        raise ValueError("source object observations missing")
    seen = set()
    for item in objects:
        if not isinstance(item, dict):
            raise ValueError("invalid source observation")
        path = item.get("path", "")
        parts = PurePosixPath(path).parts
        if not path or path.startswith("/") or ".." in parts or path in seen or str(PurePosixPath(path)) != path:
            raise ValueError("invalid or duplicate observed source path")
        if path in (MAP, STATE, PRODUCT):
            raise ValueError("status projections cannot bind their own future object")
        if not re.fullmatch(r"[0-9a-f]{40}", item.get("object", "")):
            raise ValueError("source observation requires a literal Git object")
        seen.add(path)
    material = encode(sorted(objects, key=lambda item: item["path"]))
    return {
        "schema": "hepta.control-runtime-current-state.v1",
        "module": "control.runtime",
        "canonicalStatusSource": MAP,
        "sourceBase": row["sourceBase"],
        "observedAtHead": row["observedAtHead"],
        "sourceObjectSetSha256": hashlib.sha256(material.encode()).hexdigest(),
        "components": components,
        "readOnlyProductCallerState": row["productCallerState"],
        "globalPlannerProductCallerState": row["globalPlannerProductCallerState"],
        "productionWriterState": row["productionWriterState"],
        "qualification": row["qualificationState"],
        "claimBoundary": {name: False for name in CLAIMS},
        "repositoryControlledGaps": row["repositoryControlledGaps"],
        "externalEvidenceGates": row["externalEvidenceGates"],
    }


def product_text(row, state):
    lines = [
        "# control.runtime: current product path", "",
        "Generated by `scripts/hepta-control-runtime-state.py` from the implementation map.",
        "Source composition is not an execution receipt, independent acceptance or activation.", "",
        "## Component maturity", "",
        "| Component | Source state | Product state | Qualification |",
        "| --- | --- | --- | --- |",
    ]
    for name, item in sorted(state["components"].items()):
        lines.append(f"| `{name}` | `{item['sourceState']}` | `{item['productState']}` | `{item['qualificationState']}` |")
    lines += ["", "## Named read-only path", "", "```text",
        "AgentdControlServer::run -> serve_connection",
        "  -> ContextPlanReceipts::response",
        "  -> AgentdState::response -> canonical cognitive owner read",
        "  -> plan_authenticated_context(canonical exact-ID receipt)",
        "  -> plan_observed_context -> NDU -> native plan receipt",
        "  -> host-issued response membership + monotonic expiry",
        "  -> final-use membership/profile/generation check",
        "  -> canonical owner-cut/item revalidation",
        "  -> final monotonic/profile/generation check", "```", "",
        "The wire keeps the original native plan receipt digest. The listener-owned",
        "bounded ledger binds request ID, exact query digest, owner, generation,",
        "ordered response and current retrieval/ranker profiles. It grants no effects.",
        "Canonical records determine the count and byte representation. Planner TTL",
        "uses a request-local monotonic origin; owner-store Unix validity remains separate.", "",
        "## Durable planning primitive", "",
        "`PlannerDecisionEnvelopeV1` retains five native-digest-compatible sections.",
        "`PlannerStoreV1` commits framed full bodies only after file synchronization",
        "and independently signed current-anchor compare-and-swap. Neither primitive",
        "is yet a configured production writer or an independent effect executor.", "",
        "## Unclosed repository work", "",
    ]
    lines += [f"- {gap}" for gap in state["repositoryControlledGaps"]]
    lines += ["", "## External evidence gates", ""]
    lines += [f"- {gate}" for gate in state["externalEvidenceGates"]]
    lines += ["", "Exact-head and synthetic-merge results belong to immutable CI artifacts.",
        "A generated status file never manufactures a passing native result.", ""]
    return "\n".join(lines)


def verify_source(root, row):
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env.update(GIT_CONFIG_NOSYSTEM="1", GIT_CONFIG_GLOBAL=os.devnull,
               GIT_NO_REPLACE_OBJECTS="1", GIT_NO_LAZY_FETCH="1", GIT_TERMINAL_PROMPT="0")
    def git(*args):
        return subprocess.check_output(
            ["git", "--literal-pathspecs", "-c", "core.fsmonitor=false", *args],
            cwd=root, env=env, text=True,
        ).strip()
    hidden = [item for item in git("ls-files", "-v").splitlines()
              if item and (item[0].islower() or item.startswith("S "))]
    if hidden or git("status", "--porcelain=v1", "--untracked-files=no"):
        raise ValueError("source verification requires a clean visible tracked checkout")
    for item in row["sourceObjects"]:
        if git("rev-parse", f"HEAD:{item['path']}") != item["object"]:
            raise ValueError(f"observed source object drift: {item['path']}")
    for identity in (row["sourceBase"], row["observedAtHead"]):
        if git("rev-parse", f"{identity['commit']}^{{tree}}") != identity["tree"]:
            raise ValueError("source provenance tree mismatch")
        git("merge-base", "--is-ancestor", identity["commit"], "HEAD")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--verify-source", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    row = json.loads((root / MAP).read_text(), object_pairs_hook=unique_keys)
    state = project(row)
    if args.verify_source:
        verify_source(root, row)
    outputs = {STATE: encode(state), PRODUCT: product_text(row, state)}
    for path, content in outputs.items():
        target = root / path
        if args.write:
            target.write_text(content)
        elif not target.is_file() or target.read_text() != content:
            raise ValueError(f"status projection drift: {path}")
    print(json.dumps({"module": "control.runtime", "mode": "write" if args.write else "check", "native_execution_claimed": False}))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(str(error)) from error
