#!/usr/bin/env python3
"""Compatibility entry point for kernel.authority status projections.

`qualification/kernel-authority/status_manifest.json` is the only status source
and `qualification/kernel-authority/generate_status.py` is the only generator
of machine and detailed Markdown projections.  This wrapper preserves the
historical `write` / `check` command used by repository workflows and also owns
a small navigation-only `CURRENT_STATE.md` compatibility file.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = ROOT / "qualification/kernel-authority/generate_status.py"
CURRENT_STATE_MD = ROOT / "docs/modules/kernel.authority/CURRENT_STATE.md"


def current_state_markdown() -> str:
    return """# kernel.authority current state

<!-- Generated by scripts/kernel_authority_status.py; do not edit. -->

The canonical machine-readable current state is `CURRENT_STATE.json`. Detailed
human-readable projections are `CURRENT_IMPLEMENTATION.md`, `TRACEABILITY.md`
and `STATUS.md`. All are derived from the single source
`qualification/kernel-authority/status_manifest.json` by
`qualification/kernel-authority/generate_status.py`.

This compatibility page grants no production implementation, product execution,
independent acceptance, activation or release authority.
"""


def run_generator(check: bool) -> None:
    command = [sys.executable, str(GENERATOR)]
    if check:
        command.append("--check")
    subprocess.run(command, cwd=ROOT, check=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("write", "check"))
    args = parser.parse_args()

    expected_markdown = current_state_markdown()
    try:
        run_generator(check=args.command == "check")
    except subprocess.CalledProcessError as error:
        return error.returncode or 1

    if args.command == "write":
        CURRENT_STATE_MD.write_text(expected_markdown, encoding="utf-8")
        return 0

    try:
        current = CURRENT_STATE_MD.read_text(encoding="utf-8")
    except OSError:
        current = ""
    if current != expected_markdown:
        print(
            "stale kernel.authority compatibility projection: "
            "docs/modules/kernel.authority/CURRENT_STATE.md",
            file=sys.stderr,
        )
        return 1
    print("PASS_KERNEL_AUTHORITY_STATUS_PROJECTIONS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
