#!/usr/bin/env python3
"""Extend the V2 qualification receipt with the authenticated wire candidate."""

from __future__ import annotations

import pathlib
import shutil

import memory_federation_attestation as base

base.QUALIFIED_PATHS = (
    *base.QUALIFIED_PATHS,
    "codex-rs/hepta-memory-federation-wire",
    "scripts/memory_federation_full_attestation.py",
    "scripts/run_memory_federation_qualification.sh",
)

base.COMMANDS = (
    *base.COMMANDS,
    "cargo fmt --manifest-path codex-rs/hepta-memory-federation-wire/Cargo.toml -- --check",
    "cargo metadata --manifest-path codex-rs/hepta-memory-federation-wire/Cargo.toml --format-version 1 --no-deps",
    "cargo test --manifest-path codex-rs/hepta-memory-federation-wire/Cargo.toml --lib",
    "cargo clippy --manifest-path codex-rs/hepta-memory-federation-wire/Cargo.toml --all-targets -- -D warnings",
)

_WIRE_LOCK = pathlib.Path("codex-rs/hepta-memory-federation-wire/Cargo.lock")
_ORIGINAL_EMIT_PAYLOAD = base.emit_payload
_ORIGINAL_VERIFY_PAYLOAD = base._verify_payload


def _emit_payload_with_wire_resolution(args):
    result = _ORIGINAL_EMIT_PAYLOAD(args)
    if not _WIRE_LOCK.is_file():
        return result

    output = pathlib.Path(args.output)
    copied_lock = output / "wire-Cargo.lock"
    shutil.copyfile(_WIRE_LOCK, copied_lock)
    attestation_path = output / "attestation.json"
    attestation = base._read_json(attestation_path)
    evidence = base._require_mapping("evidence", attestation.get("evidence"))
    evidence["wireCargoLock"] = copied_lock.name
    evidence["wireCargoLockSha256"] = base._sha256_bytes(copied_lock.read_bytes())
    digest = base._write_json(attestation_path, attestation)
    (output / "attestation.sha256").write_text(
        f"{digest}  attestation.json\n", encoding="utf-8"
    )
    return result


def _verify_payload_with_wire_resolution(path, value):
    document = _ORIGINAL_VERIFY_PAYLOAD(path, value)
    evidence = base._require_mapping("evidence", document.get("evidence"))
    lock_path_value = evidence.get("wireCargoLock")
    lock_digest_value = evidence.get("wireCargoLockSha256")
    if (lock_path_value is None) != (lock_digest_value is None):
        raise base.AttestationError(
            "wire Cargo.lock evidence requires both a path and SHA-256 digest"
        )
    if lock_path_value is not None:
        lock_path = base._resolve_evidence_file(path, lock_path_value)
        lock_digest = base._require_hex(
            "evidence.wireCargoLockSha256",
            lock_digest_value,
            base._SHA256_RE,
        )
        if base._sha256_bytes(lock_path.read_bytes()) != lock_digest:
            raise base.AttestationError("wire Cargo.lock evidence digest mismatch")
        lock_text = lock_path.read_text(encoding="utf-8")
        if not lock_text.startswith("# This file is automatically @generated by Cargo."):
            raise base.AttestationError("wire Cargo.lock evidence is not a Cargo lockfile")
    return document


base.emit_payload = _emit_payload_with_wire_resolution
base._verify_payload = _verify_payload_with_wire_resolution


if __name__ == "__main__":
    raise SystemExit(base.main())
