#!/usr/bin/env python3
"""Render fail-closed platform.wire lifecycle state from source-bound receipts."""
from __future__ import annotations
import argparse, json
from pathlib import Path
from platform_wire_receipt_subject import require_selected_source
from platform_wire_status_receipts import (
    SCHEMA, DESIGN, IMPL, WORK, ACCEPT, PERF, PROD, load,
)

def evaluate(a):
    root=Path(a.root).resolve(); missing_d=[x for x in DESIGN if not (root/x).is_file()]; missing_i=[x for x in IMPL if not (root/x).is_file()]
    e=load(a.exact_head,"platform-wire-exact-head"); m=load(a.synthetic_merge,"platform-wire-synthetic-merge"); t=load(a.target_host,"platform-wire-target-host"); p=load(a.performance,PERF); d=load(a.production,PROD); r=load(a.reviewer_acceptance,"platform-wire-reviewer-acceptance"); o=load(a.operations_acceptance,"platform-wire-operations-acceptance"); z=load(a.release,"platform-wire-release")
    allr=[x for x in (e,m,t,p,d,r,o,z) if x]
    sources={x["source_sha"] for x in allr}
    if len(sources)>1: raise ValueError("receipt source disagreement")
    source=next(iter(sources),None)
    if source: require_selected_source(root,source,getattr(a,"expected_source_sha",None))
    designed=not missing_d; implemented=designed and not missing_i; qualified=implemented and all(x and x["passed"] for x in (e,m,t)); distinct=r and o and r["approver"] and o["approver"] and r["approver"].casefold()!=o["approver"].casefold(); accepted=bool(qualified and p and p["passed"] and d and d["passed"] and r and r["passed"] and o and o["passed"] and distinct); released=bool(accepted and z and z["passed"])
    def state(x):
        if not x:return None
        out={k:x[k] for k in ("kind","source_sha","tested_sha","status","passed","path")}; q=x["payload"]
        for n in ("run_id","run_attempt","workflow","workflow_ref","lane","base_sha","environment","host_profile","deployment_profile","runner_name","runner_os","runner_arch","measurement_run_id","measurement_workflow_path","measurement_artifact","measurement_artifact_digest","observation_run_id","observation_workflow_path","observation_artifact","observation_artifact_digest","plan_sha256","report_sha256","path_count","scenario_count","deployment_id","approver","approver_role","approved_at","release_id","artifact_digest","evidence_url"):
            if n in q:out[n]=q[n]
        out["schema"]=SCHEMA; return out
    return {"schema":"hepta.platform-wire.status.v2","source_sha":source,"states":{"designed":designed,"implemented":implemented,"qualified":qualified,"accepted":accepted,"released":released},"missing":{"design":missing_d,"implementation":missing_i},"evidence":{"exact_head":state(e),"synthetic_merge":state(m),"target_host":state(t),"performance":state(p),"production":state(d),"reviewer_acceptance":state(r),"operations_acceptance":state(o),"release":state(z)}}


def markdown(s):
    v=s["states"]; lines=["# platform.wire evidence-derived lifecycle status","","This file is generated by `scripts/platform_wire_status.py`; do not edit lifecycle booleans by hand.","","| State | Value | Derivation |","|---|---:|---|",f"| Designed | `{'true' if v['designed'] else 'false'}` | repository design/document closure |",f"| Implemented | `{'true' if v['implemented'] else 'false'}` | required native source closure |",f"| Qualified | `{'true' if v['qualified'] else 'false'}` | exact-head + synthetic-merge + protected target-host receipts |",f"| Accepted | `{'true' if v['accepted'] else 'false'}` | qualified state + passed five-path performance and production-composition receipts + distinct independent reviewer and operations receipts |",f"| Released | `{'true' if v['released'] else 'false'}` | accepted state + release receipt |","","## Evidence inputs",""]
    for n in s["evidence"]:
        r=s["evidence"][n]; lines.append(f"- `{n}`: absent" if r is None else f"- `{n}`: `{r['status']}`; source `{r['source_sha']}`; tested `{r['tested_sha']}`")
    lines += ["","The protected performance and production-composition contracts are documented in [PERFORMANCE_INTAKE_20260929.md](PERFORMANCE_INTAKE_20260929.md) and [PRODUCTION_INTAKE_20260929.md](PRODUCTION_INTAKE_20260929.md).","","Absent, malformed, failing or source-inconsistent receipts fail closed. Accepted/Released require both the five-path paired performance receipt and the eight-scenario production-composition receipt. Reviewer and operations acceptance must be issued by distinct identities independent of the implementation author; source code and ordinary CI cannot self-attest either receipt.",""]
    return "\n".join(lines)

def args():
    p=argparse.ArgumentParser(); sub=p.add_subparsers(dest="cmd",required=True)
    r=sub.add_parser("render"); r.add_argument("--root",default="."); r.add_argument("--expected-source-sha")
    for n in ("exact-head","synthetic-merge","target-host","performance","production","reviewer-acceptance","operations-acceptance","release"):r.add_argument("--"+n)
    r.add_argument("--format",choices=("json","markdown"),required=True);r.add_argument("--output",required=True)
    c=sub.add_parser("check-doc");c.add_argument("--root",default=".");c.add_argument("--document",default="docs/modules/platform.wire/STATUS.md")
    v=sub.add_parser("validate-receipt");v.add_argument("--path",required=True);v.add_argument("--kind",required=True,choices=sorted(WORK|set(ACCEPT)|{"platform-wire-release"}))
    sub.add_parser("self-test");return p.parse_args()

def main():
    a=args()
    if a.cmd=="self-test":
        from platform_wire_status_selftest import run
        run(evaluate); return 0
    if a.cmd=="validate-receipt":load(a.path,a.kind);return 0
    if a.cmd=="render":
        s=evaluate(a);Path(a.output).write_text((json.dumps(s,indent=2,sort_keys=True)+"\n") if a.format=="json" else markdown(s));return 0
    x=argparse.Namespace(root=a.root,expected_source_sha=None,exact_head=None,synthetic_merge=None,target_host=None,performance=None,production=None,reviewer_acceptance=None,operations_acceptance=None,release=None)
    expected=markdown(evaluate(x)); actual=(Path(a.root)/a.document).read_text()
    if actual!=expected:raise SystemExit(f"{a.document} is stale; regenerate it with platform_wire_status.py")
    return 0
if __name__=="__main__":raise SystemExit(main())
