#!/usr/bin/env python3
"""Render and verify the fail-closed platform.types implementation status."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import subprocess
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC_ROOT = ROOT / "docs" / "modules" / "platform.types"
SOURCE = DOC_ROOT / "implementation_status_source.json"
MARKDOWN = DOC_ROOT / "IMPLEMENTATION_STATUS.md"
GENERATOR_VERSION = "platform_types_implementation_status.py/v1"


def load_source() -> dict[str, Any]:
    value = json.loads(SOURCE.read_text(encoding="utf-8"))
    required = {
        "schema",
        "spec_version",
        "owner_migration",
        "qualification",
        "approval_sha",
        "activation",
    }
    if set(value) != required:
        raise ValueError(f"status source keys must be exactly {sorted(required)}")
    if value["schema"] != "platform.types/implementation-status-source/v1":
        raise ValueError("unsupported status source schema")
    if value["spec_version"] != "platform.types/v2":
        raise ValueError("unsupported platform.types specification")
    if value["owner_migration"] not in {"complete", "in_progress", "blocked"}:
        raise ValueError("invalid owner_migration")
    if value["qualification"] != "unqualified":
        raise ValueError("checked-in source may not assert qualification")
    if value["approval_sha"] is not None:
        raise ValueError("checked-in source may not assert an approval SHA")
    if value["activation"] is not False:
        raise ValueError("checked-in source may not assert activation")
    return value


def render_markdown(source: dict[str, Any]) -> str:
    owner_migration = source["owner_migration"]
    return f"""<!-- Generated by scripts/platform_types_implementation_status.py. Do not edit directly. -->
# platform.types Implementation Status

Status schema: `platform.types/implementation-status/v1`  
Specification: [`SPEC_V2.md`](./SPEC_V2.md)  
Source: [`implementation_status_source.json`](./implementation_status_source.json)

This is the single current entry point for implementation and qualification status. It is deliberately fail-closed. A checked-in Markdown file cannot attest to the commit that contains itself, so exact source SHA, workflow run IDs, timestamps, and tool versions are emitted by CI as evidence artifacts. The checked-in state below describes the repository posture until those exact-source artifacts, independent approval, merge, post-merge verification, and activation all exist.

## Current checked-in posture

```yaml
spec_version: {source['spec_version']}
source_sha: generated-by-ci
main_sha: generated-by-ci
owner_migration: {owner_migration}
required_workflow_runs: generated-by-ci
qualification: {source['qualification']}
approval_sha: null
activation: false
generated_at: generated-by-ci
generator_version: {GENERATOR_VERSION}
```

`generated-by-ci` is not a wildcard and must never be interpreted as satisfied. Missing, stale, mixed-SHA, or unverifiable evidence leaves the module unqualified.

## State model

The lifecycle is monotone and fail-closed:

1. **Source candidate** — source and generated artifacts exist, but no qualification claim is made.
2. **Exact-source verified** — required checks passed against one immutable candidate SHA.
3. **Synthetic-merge verified** — required checks passed against a fixed merge of that candidate and the recorded base SHA.
4. **Independently approved** — a non-author approval targets the same immutable candidate SHA.
5. **Merged** — the reviewed candidate is in `main`.
6. **Post-merge verified** — required checks passed against the immutable merge SHA.
7. **Activated** — the activation pointer names that verified merge SHA.

Failure or absence at any stage prevents all later status claims. A workflow-generated future tree, local dirty tree, author self-approval, approval of an older SHA, or archived probe cannot satisfy a stage.

## Required exact-source evidence

For one immutable candidate SHA, CI must record at least:

- source lock and clean checkout;
- formatting and lint checks;
- `hepta-types` unit and documentation tests;
- strict wire and canonical round-trip tests;
- mandatory consumer compile/tests, including `hepta-ndu` numeric snapshot ownership;
- public API inventory and compatibility matrix regeneration with a clean worktree;
- protocol/catalog code generation and vector verification;
- resource/boundary and negative fixtures;
- MSRV verification;
- native-platform smoke checks;
- Miri and fuzz targets where designated;
- provenance/evidence bundle validation;
- legacy API and documentation-contract gates.

Every evidence record must carry the source SHA, base/main SHA where relevant, workflow/run identity, toolchain versions, and artifact digests. Evidence from different source SHAs cannot be combined into a green result.

## Owner migration

Owner migration is complete only when all mandatory consumers use the current typed APIs and protocol/catalog contracts without compatibility-only fallbacks. The consumer ledger is maintained in [`MIGRATION_V1_TO_V2.md`](./MIGRATION_V1_TO_V2.md). A green core crate with a failing mandatory consumer is not a qualified module.

## Approval and activation

Approval must be supplied by an independent reviewer and must target the exact candidate SHA after the final code change. Automation may verify the approval; it may not manufacture or substitute for it.

Activation remains `false` until the reviewed candidate is merged, the merge SHA passes post-merge qualification, and the activation pointer is updated to that SHA. Documentation edits alone cannot activate the module.

## Generated status artifact

CI emits a machine-readable status record with this shape:

```json
{{
  "schema": "platform.types/implementation-status/v1",
  "spec_version": "platform.types/v2",
  "source_sha": "<40-hex exact candidate or merge SHA>",
  "main_sha": "<40-hex base/main SHA>",
  "owner_migration": "complete|in_progress|blocked",
  "required_workflow_runs": [{{"name": "...", "run_id": 0, "conclusion": "success|pending|failure"}}],
  "qualification": "qualified|unqualified",
  "approval_sha": "<40-hex SHA or null>",
  "activation": false,
  "generated_at": "<RFC3339 UTC>",
  "generator_version": "{GENERATOR_VERSION}"
}}
```

The generator validates consistency rather than copying optimistic prose. If any required field is unavailable, it emits an unqualified result or fails.

## Supporting evidence

Detailed qualification design and historical results remain available in the supporting files listed by [`README.md`](./README.md). They are evidence inputs and historical records, not parallel current-status authorities.
"""


def git_output(*args: str) -> str:
    return subprocess.check_output(
        ["git", *args], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
    ).strip()


def exact_status(source: dict[str, Any]) -> dict[str, Any]:
    source_sha = os.environ.get("PLATFORM_TYPES_SOURCE_SHA") or git_output("rev-parse", "HEAD")
    main_sha = os.environ.get("PLATFORM_TYPES_MAIN_SHA")
    if not main_sha:
        try:
            main_sha = git_output("rev-parse", "origin/main")
        except (OSError, subprocess.CalledProcessError) as error:
            raise RuntimeError(
                "main SHA is unavailable; set PLATFORM_TYPES_MAIN_SHA"
            ) from error

    run_id_raw = os.environ.get("GITHUB_RUN_ID")
    workflow = os.environ.get("GITHUB_WORKFLOW", "local-status-generation")
    required_runs: list[dict[str, Any]] = []
    if run_id_raw and run_id_raw.isdigit():
        required_runs.append(
            {"name": workflow, "run_id": int(run_id_raw), "conclusion": "pending"}
        )

    return {
        "schema": "platform.types/implementation-status/v1",
        "spec_version": source["spec_version"],
        "source_sha": source_sha,
        "main_sha": main_sha,
        "owner_migration": source["owner_migration"],
        "required_workflow_runs": required_runs,
        "qualification": "unqualified",
        "approval_sha": None,
        "activation": False,
        "generated_at": dt.datetime.now(dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "generator_version": GENERATOR_VERSION,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--emit-json", type=pathlib.Path)
    args = parser.parse_args()
    if not (args.check or args.write or args.emit_json):
        parser.error("select --check, --write, or --emit-json")

    source = load_source()
    rendered = render_markdown(source)

    if args.write:
        MARKDOWN.write_text(rendered, encoding="utf-8")
    if args.check:
        current = MARKDOWN.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "platform.types implementation status: generated Markdown drift",
                file=sys.stderr,
            )
            return 1
    if args.emit_json:
        args.emit_json.parent.mkdir(parents=True, exist_ok=True)
        args.emit_json.write_text(
            json.dumps(exact_status(source), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    print("platform.types implementation status: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
