"""Run the real fuzz-gate argv on an isolated dependency-free Cargo fixture."""

import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest

from cognitive_read_evidence import commands


@unittest.skipUnless(shutil.which("cargo"), "Cargo is required for lock enforcement")
class FuzzLockTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.fuzz = self.root / "codex-rs/hepta-cognitive-read/fuzz"
        self.fuzz.mkdir(parents=True)
        self.manifest = self.fuzz / "Cargo.toml"
        self.manifest.write_text(
            '[package]\nname="fuzz-lock-fixture"\nversion="0.0.0"\n'
            'edition="2024"\n[lib]\npath="lib.rs"\n[workspace]\n'
        )
        (self.fuzz / "lib.rs").write_text("pub fn fixture() {}\n")
        self.lock = self.fuzz / "Cargo.lock"
        self.lock_text = (
            "# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\n"
            'version = 4\n\n[[package]]\nname = "fuzz-lock-fixture"\n'
            'version = "0.0.0"\n'
        )

    def execute(self):
        argv = commands("a" * 40, self.root / "evidence")["fuzz-harness"]
        return subprocess.run(
            [*argv, "--offline"],
            cwd=self.root,
            env={**os.environ, "CARGO_TARGET_DIR": str(self.root / "target")},
            text=True,
            capture_output=True,
            timeout=30,
        )

    def test_missing_fuzz_lock_fails_without_authoring_source(self):
        result = self.execute()
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse(self.lock.exists())
        self.assertIn("--locked", result.stderr)

    def test_changed_manifest_cannot_rewrite_frozen_resolution(self):
        self.lock.write_text(self.lock_text)
        self.manifest.write_text(
            self.manifest.read_text().replace('version="0.0.0"', 'version="0.0.1"')
        )
        result = self.execute()
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(self.lock.read_text(), self.lock_text)

    def test_frozen_fuzz_fixture_checks_without_changing_inputs(self):
        self.lock.write_text(self.lock_text)
        inputs = {path: path.read_bytes() for path in self.fuzz.iterdir()}
        result = self.execute()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(
            {path: path.read_bytes() for path in self.fuzz.iterdir()}, inputs
        )


if __name__ == "__main__":
    unittest.main()
