"""Lane G engineering-control implementation exports."""

from .assimilation import (
    AssimilationProposal,
    DebianSandboxAdapter,
    ExternalManifestCandidate,
    OwnerConsentReceipt,
    SandboxParityReceipt,
    SandboxObservation,
    TypedOperation,
    build_manifest_candidate,
    propose_dormant_assimilation,
    synthesize_read_only_contracts,
    validate_consent,
)
from .candidate import (
    Candidate,
    CandidateEnvelope,
    Mutation,
    MutationSet,
    SandboxReceipt,
    generate_candidates,
    sandbox_candidate,
)
from .control_plane import (
    EngineeringError,
    EngineeringStore,
    LeaseReceipt,
    ScheduleReceipt,
    WorkEnvelope,
    WorkPackage,
    bounded_tuple,
    canonical_json,
    canonical_repo_path,
    canonical_paths,
    checked_id,
    checked_sha256,
    path_is_within,
    path_sets_overlap,
    paths_overlap,
    semantic_digest,
)
from .external_controls import (
    AuditAnchorAttestation,
    DistributedFenceReceipt,
    KeyCustodyReceipt,
    ProductionControlDecision,
    verify_distributed_fence,
    verify_external_audit_anchor,
    verify_external_key_custody,
    verify_production_controls,
)
from .evidence import (
    CanonicalSourceReceipt,
    EvidenceDecision,
    EvaluatorIndependenceReceipt,
    ExecutionReceipt,
    HmacTrustStore,
    SignatureTrustStore,
    verify_integration_evidence,
)
from .facade import (
    ReviewRequest,
    execute_candidate_sandbox,
    generate_candidate,
    issue_work_envelope,
    publish_audit_projection,
    schedule_ready_packages,
)
from .mutation_testing import (
    MutationTestingReceipt,
    run_mutation_testing,
)
from .orchestration import (
    CompletionReceipt,
    EngineeringAssignment,
    EngineeringCapacity,
    EngineeringPlan,
    EngineeringWorkPackage,
    MergeQueueProposal,
    ReviewCapacity,
    WorkerProfile,
    issue_repository_work_envelope,
    issue_signed_work_envelope,
    plan_engineering_work,
)
from .sandbox_control import (
    SandboxCoordinator,
    SandboxExecutionPolicy,
    SandboxExecutionResult,
)
from .production import (
    ProductionReadinessDecision,
    ProductionReadinessFacts,
    evaluate_production_readiness,
)
from .hardening import (
    AttestedSandboxParity,
    BoundEvidenceDecision,
    CandidateEvidenceBindingReceipt,
    OwnerConsentAttestation,
    SandboxParityAttestation,
    assignment_frontier,
    consent_payload_digest,
    hardened_execute_candidate_sandbox,
    hardened_sandbox_candidate,
)

# The store owns its schema and transactions directly. Public composition uses
# authenticated evidence; candidate.py remains the sole sandbox executor.
from .closure import prepare_assimilation_candidate
from .seal import (
    SealedCandidateEvidence,
    bind_candidate_evidence,
    record_integration_decision,
    request_independent_review,
    verify_sealed_candidate_evidence,
)

# Legacy public names use the current authenticated boundary too. Lower-layer
# composition helpers are implementation details, not an alternate public gate.
hardened_prepare_assimilation_candidate = prepare_assimilation_candidate
hardened_record_integration_decision = record_integration_decision
hardened_request_independent_review = request_independent_review

__all__ = [
    "AssimilationProposal",
    "DebianSandboxAdapter",
    "AttestedSandboxParity",
    "BoundEvidenceDecision",
    "Candidate",
    "CandidateEnvelope",
    "CandidateEvidenceBindingReceipt",
    "AuditAnchorAttestation",
    "CanonicalSourceReceipt",
    "CompletionReceipt",
    "EngineeringAssignment",
    "EngineeringCapacity",
    "EngineeringPlan",
    "EngineeringWorkPackage",
    "DistributedFenceReceipt",
    "EngineeringError",
    "EngineeringStore",
    "EvaluatorIndependenceReceipt",
    "EvidenceDecision",
    "ExecutionReceipt",
    "ExternalManifestCandidate",
    "HmacTrustStore",
    "SignatureTrustStore",
    "KeyCustodyReceipt",
    "LeaseReceipt",
    "MergeQueueProposal",
    "Mutation",
    "MutationTestingReceipt",
    "MutationSet",
    "OwnerConsentAttestation",
    "OwnerConsentReceipt",
    "ProductionControlDecision",
    "ProductionReadinessDecision",
    "ProductionReadinessFacts",
    "ReviewCapacity",
    "ReviewRequest",
    "SandboxCoordinator",
    "SandboxExecutionPolicy",
    "SandboxExecutionResult",
    "SandboxParityAttestation",
    "SandboxParityReceipt",
    "SandboxObservation",
    "SandboxReceipt",
    "ScheduleReceipt",
    "SealedCandidateEvidence",
    "TypedOperation",
    "WorkerProfile",
    "WorkEnvelope",
    "WorkPackage",
    "assignment_frontier",
    "bind_candidate_evidence",
    "bounded_tuple",
    "build_manifest_candidate",
    "canonical_json",
    "canonical_paths",
    "canonical_repo_path",
    "checked_id",
    "checked_sha256",
    "consent_payload_digest",
    "evaluate_production_readiness",
    "execute_candidate_sandbox",
    "generate_candidate",
    "generate_candidates",
    "hardened_execute_candidate_sandbox",
    "hardened_prepare_assimilation_candidate",
    "hardened_record_integration_decision",
    "hardened_request_independent_review",
    "hardened_sandbox_candidate",
    "issue_repository_work_envelope",
    "issue_signed_work_envelope",
    "issue_work_envelope",
    "plan_engineering_work",
    "path_is_within",
    "path_sets_overlap",
    "paths_overlap",
    "prepare_assimilation_candidate",
    "propose_dormant_assimilation",
    "publish_audit_projection",
    "record_integration_decision",
    "run_mutation_testing",
    "request_independent_review",
    "sandbox_candidate",
    "schedule_ready_packages",
    "semantic_digest",
    "synthesize_read_only_contracts",
    "validate_consent",
    "verify_distributed_fence",
    "verify_external_audit_anchor",
    "verify_external_key_custody",
    "verify_integration_evidence",
    "verify_production_controls",
    "verify_sealed_candidate_evidence",
]
