[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-control-plane"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_control_plane"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-hepta-contracts = { workspace = true }
codex-hepta-ndu = { path = "../hepta-ndu" }
codex-hepta-types = { path = "../hepta-types" }

[dev-dependencies]
ed25519-dalek = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
