//! B1 topology, Basil-profile, and identity-boundary contracts.
//!
//! This module is intentionally a qualification-only boundary.  It describes
//! the small set of routes and caller evidence that an eventual Basil fork may
//! register; it does not open a socket, load a key, or grant authority.  The
//! validator is therefore conservative: an unknown route, an optional route
//! without an explicit process-bound permit, a missing registered key, or a
//! caller that only presents a service UID is rejected.

use serde::Deserialize;
use serde::Serialize;

use crate::Sha256Digest;

use super::AUTHBUS_CONTRACT_SCHEMA_VERSION;
use super::AuthBusContractError;
use super::canonical_json;
use super::contract_domain;
use super::domain_digest;
use super::validate_digest;
use super::validate_text;
use super::validate_window;

/// B1 uses the same versioned AuthBus wire family as B0/B2.
pub const AUTHBUS_B1_CONTRACT_SCHEMA_VERSION: u32 = AUTHBUS_CONTRACT_SCHEMA_VERSION;
/// Canonical Basil profile selected by AUTHBUS.11 v1.3.
pub const AUTHBUS_B1_PROFILE_ID: &str = "hepta-basil-host-minimal-v1";

/// Native Basil routes that may be registered in the minimal profile.
pub const BASIL_B1_ALLOWED_ROUTES: &[&str] = &[
    "/basil.broker.v1.SigningService/Sign",
    "/basil.broker.v1.SigningService/Verify",
    "/basil.broker.v1.SigningService/GetPublicKey",
    "/basil.broker.v1.AdminService/Health",
];

/// Routes that require an explicit process-bound permit in addition to the
/// static profile.  They are not allowed by the default route check.
pub const BASIL_B1_OPTIONAL_PROCESS_BOUND_ROUTES: &[&str] =
    &["/basil.broker.v1.AeadService/Decrypt"];

/// Basil routes and families that are denied by the profile.  The list is an
/// exact, ordered projection of the active B1 route inventory; unknown routes
/// are denied even when they are not listed here.
pub const BASIL_B1_DENIED_ROUTES: &[&str] = &[
    "/basil.broker.v1.SigningService/NewKey",
    "/basil.broker.v1.SigningService/Import",
    "/basil.broker.v1.SigningService/ImportSet",
    "/basil.broker.v1.SecretService/GetSecret",
    "/basil.broker.v1.SecretService/SetSecret",
    "/basil.broker.v1.SecretService/RotateSecret",
    "/basil.broker.v1.SecretService/ListCatalog",
    "/basil.broker.v1.AeadService/Encrypt",
    "/basil.broker.v1.AeadService/WrapEnvelope",
    "/basil.broker.v1.AeadService/UnwrapEnvelope",
    "/basil.broker.v1.AeadService/UnsealCose",
    "/basil.broker.v1.MintingService/MintJwt",
    "/basil.broker.v1.MintingService/IssueCertificate",
    "/basil.broker.v1.InvocationService/Invoke",
    "/basil.broker.v1.InvocationService/GetInvocationChallenge",
    "/basil.broker.v1.InvocationService/GetInvocationCapabilities",
    "/basil.broker.v1.AdminService/Status",
    "/basil.broker.v1.AdminService/Readiness",
    "/basil.broker.v1.AdminService/Watch",
    "/basil.broker.v1.AdminService/Reload",
    "/basil.broker.v1.AdminService/Explain",
    "/basil.broker.v1.AdminService/Revoke",
    "/basil.broker.v1.AdminService/ListConnections",
    "/basil.broker.v1.AdminService/DropConnections",
    "/basil.broker.v1.NatsService/*",
    "/basil.broker.v1.NixCacheService/*",
    "/SpiffeWorkloadAPI/*",
    "/envoy.service.secret.v3.SecretDiscoveryService/*",
    "UnknownFutureRPC",
];

fn error(message: impl Into<String>) -> AuthBusContractError {
    AuthBusContractError::new(message)
}

fn validate_id(value: &str, label: &str) -> Result<(), AuthBusContractError> {
    validate_text(value, label, /*max_bytes*/ 512)
}

fn validate_nonzero(value: u64, label: &str) -> Result<(), AuthBusContractError> {
    if value == 0 {
        return Err(error(format!("{label} must be non-zero")));
    }
    Ok(())
}

fn route_set_digest(
    allowed: &[String],
    optional: &[String],
    denied: &[String],
) -> Result<Sha256Digest, AuthBusContractError> {
    #[derive(Serialize)]
    struct RouteSet<'a> {
        allowed: &'a [String],
        optional_process_bound: &'a [String],
        denied: &'a [String],
    }
    let bytes = canonical_json(&RouteSet {
        allowed,
        optional_process_bound: optional,
        denied,
    })?;
    Ok(domain_digest("basil-route-set", &bytes))
}

/// Result of classifying a Basil route before any runtime permit check.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BasilRouteClass {
    Allowed,
    OptionalProcessBound,
    Denied,
}

/// Whether key material may be generated by the Basil profile.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BasilKeyGenerationMode {
    Forbidden,
}

/// External key registration metadata.  The private key itself is never
/// representable in this type.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BasilKeyRegistration {
    pub key_id: String,
    pub key_epoch: u64,
    pub signature_alg: String,
    pub key_type: String,
    pub signer_usage_domain: String,
    pub public_key_digest: Sha256Digest,
    pub backend_binding_digest: Sha256Digest,
}

impl BasilKeyRegistration {
    /// Validate a pre-registered backend key reference without touching the
    /// backend or attempting key generation/import.
    pub fn validate(&self) -> Result<(), AuthBusContractError> {
        validate_id(&self.key_id, "Basil key id")?;
        validate_nonzero(self.key_epoch, "Basil key epoch")?;
        validate_id(&self.signature_alg, "Basil signature algorithm")?;
        validate_id(&self.key_type, "Basil key type")?;
        validate_id(&self.signer_usage_domain, "Basil signer usage domain")?;
        validate_digest(&self.public_key_digest, "Basil public key")?;
        validate_digest(&self.backend_binding_digest, "Basil backend binding")
    }
}

/// The exact route/key-generation profile projected from AUTHBUS.11 B1.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BasilServiceProfile {
    pub schema_version: u32,
    pub profile_id: String,
    pub allowed_routes: Vec<String>,
    pub optional_process_bound_routes: Vec<String>,
    pub denied_routes: Vec<String>,
    pub route_set_digest: Sha256Digest,
    pub descriptor_digest: Sha256Digest,
    pub key_generation: BasilKeyGenerationMode,
    #[serde(default)]
    pub authority: bool,
}

impl BasilServiceProfile {
    /// Construct the immutable default-deny profile with a caller-supplied
    /// descriptor digest.  The digest is observed descriptor evidence; it is
    /// not a signing key or an authority grant.
    pub fn qualification(descriptor_digest: Sha256Digest) -> Result<Self, AuthBusContractError> {
        let allowed_routes = BASIL_B1_ALLOWED_ROUTES
            .iter()
            .map(|route| (*route).to_string())
            .collect::<Vec<_>>();
        let optional_process_bound_routes = BASIL_B1_OPTIONAL_PROCESS_BOUND_ROUTES
            .iter()
            .map(|route| (*route).to_string())
            .collect::<Vec<_>>();
        let denied_routes = BASIL_B1_DENIED_ROUTES
            .iter()
            .map(|route| (*route).to_string())
            .collect::<Vec<_>>();
        let route_set_digest = route_set_digest(
            &allowed_routes,
            &optional_process_bound_routes,
            &denied_routes,
        )?;
        Ok(Self {
            schema_version: AUTHBUS_B1_CONTRACT_SCHEMA_VERSION,
            profile_id: AUTHBUS_B1_PROFILE_ID.to_string(),
            allowed_routes,
            optional_process_bound_routes,
            denied_routes,
            route_set_digest,
            descriptor_digest,
            key_generation: BasilKeyGenerationMode::Forbidden,
            authority: false,
        })
    }

    /// Validate the exact allow/optional/deny inventory and default-deny
    /// properties required by B1.
    pub fn validate(&self) -> Result<(), AuthBusContractError> {
        if self.schema_version != AUTHBUS_B1_CONTRACT_SCHEMA_VERSION {
            return Err(error("unsupported B1 Basil profile schema version"));
        }
        if self.profile_id != AUTHBUS_B1_PROFILE_ID {
            return Err(error("unexpected B1 Basil profile id"));
        }
        if self.authority {
            return Err(error("B1 Basil profile cannot carry authority"));
        }
        if self.key_generation != BasilKeyGenerationMode::Forbidden {
            return Err(error("B1 key generation must remain forbidden"));
        }
        validate_digest(&self.descriptor_digest, "B1 descriptor")?;
        let expected_allowed = BASIL_B1_ALLOWED_ROUTES
            .iter()
            .map(|route| (*route).to_string())
            .collect::<Vec<_>>();
        let expected_optional = BASIL_B1_OPTIONAL_PROCESS_BOUND_ROUTES
            .iter()
            .map(|route| (*route).to_string())
            .collect::<Vec<_>>();
        let expected_denied = BASIL_B1_DENIED_ROUTES
            .iter()
            .map(|route| (*route).to_string())
            .collect::<Vec<_>>();
        if self.allowed_routes != expected_allowed
            || self.optional_process_bound_routes != expected_optional
            || self.denied_routes != expected_denied
        {
            return Err(error(
                "B1 Basil route inventory does not match canonical profile",
            ));
        }
        let expected_digest = route_set_digest(
            &self.allowed_routes,
            &self.optional_process_bound_routes,
            &self.denied_routes,
        )?;
        if self.route_set_digest != expected_digest {
            return Err(error("B1 Basil route-set digest mismatch"));
        }
        Ok(())
    }

    /// Classify a route.  Both listed denied routes and unknown routes are
    /// denied; no caller can opt into an unknown future RPC by naming it.
    pub fn classify_route(&self, route: &str) -> BasilRouteClass {
        if self
            .allowed_routes
            .iter()
            .any(|candidate| candidate == route)
        {
            BasilRouteClass::Allowed
        } else if self
            .optional_process_bound_routes
            .iter()
            .any(|candidate| candidate == route)
        {
            BasilRouteClass::OptionalProcessBound
        } else {
            BasilRouteClass::Denied
        }
    }

    /// Authorize only static routes.  Optional process-bound routes remain
    /// denied unless a later adapter performs its separate permit check.
    pub fn allows_static_route(&self, route: &str) -> Result<(), AuthBusContractError> {
        self.validate()?;
        if self.classify_route(route) == BasilRouteClass::Allowed {
            Ok(())
        } else {
            Err(error(format!(
                "B1 route is not statically allowed: {route}"
            )))
        }
    }

    /// Require a pre-registered key.  `None` is always a fail-closed error;
    /// this method never generates, imports, or substitutes key material.
    pub fn require_registered_key(
        &self,
        registration: Option<&BasilKeyRegistration>,
    ) -> Result<(), AuthBusContractError> {
        self.validate()?;
        let Some(registration) = registration else {
            return Err(error("B1 readiness requires a registered backend key"));
        };
        registration.validate()
    }

    /// Canonical bytes for profile/descriptor review.
    pub fn canonical_bytes(&self) -> Result<Vec<u8>, AuthBusContractError> {
        self.validate()?;
        canonical_json(self)
    }

    /// Domain-separated digest of the validated profile.
    pub fn digest(&self) -> Result<Sha256Digest, AuthBusContractError> {
        Ok(domain_digest(
            &contract_domain("basil-service-profile"),
            &self.canonical_bytes()?,
        ))
    }
}

/// Platform evidence used to bind a caller beyond a raw service UID.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[serde(deny_unknown_fields)]
pub enum IdentityPeerEvidence {
    /// Linux `SO_PEERCRED` plus agentd generation, launch nonce and process
    /// start-time/pidfd evidence.  UID/GID alone is deliberately insufficient.
    LinuxPeer {
        peer_uid: u32,
        peer_gid: u32,
        peer_pid: u32,
        agentd_generation: u64,
        launch_nonce_sha256: Sha256Digest,
        pid_start_time_ticks: u64,
        pidfd_bound: bool,
    },
    /// macOS development adapter evidence.  The raw audit token is not carried.
    MacAuditToken { token_sha256: Sha256Digest },
    /// A fixed service-UID bridge, accepted only as a bridge label because the
    /// outer identity claims still carry nonce/audience/epoch/fence evidence.
    ServiceUidBridge { service_uid_sha256: Sha256Digest },
    /// Explicitly model the unsafe same-UID shortcut so it can be rejected and
    /// never mistaken for per-agent identity.
    SameUidOnly,
}

/// Canonical identity claims for a process-bound AuthBus request.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IdentityBinding {
    pub schema_version: u32,
    pub binding_id: String,
    pub tenant_id: String,
    pub workspace_id: String,
    pub agent_id: String,
    pub service_id: String,
    pub node_id: String,
    pub generation: u64,
    pub launch_nonce_sha256: Sha256Digest,
    pub session_id: String,
    pub operation: String,
    pub secret_ref_allowlist_digest: Sha256Digest,
    pub epoch: u64,
    pub nonce_sha256: Sha256Digest,
    pub key_id: String,
    pub capability_digest: Sha256Digest,
    pub intent_digest: Sha256Digest,
    pub transcript_digest: Sha256Digest,
    pub audience: String,
    pub issued_at_unix_seconds: u64,
    pub not_before_unix_seconds: u64,
    pub expires_at_unix_seconds: u64,
    pub policy_digest: Sha256Digest,
    pub hnl_attestation_digest: Sha256Digest,
    pub service_identity_digest: Sha256Digest,
    pub subject_digest: Sha256Digest,
    pub authority_epoch: u64,
    pub owner_epoch: u64,
    pub fencing_token_sha256: Sha256Digest,
    pub peer: IdentityPeerEvidence,
    #[serde(default)]
    pub authority: bool,
}

#[derive(Serialize)]
struct IdentitySubject<'a> {
    tenant_id: &'a str,
    workspace_id: &'a str,
    agent_id: &'a str,
    service_id: &'a str,
    node_id: &'a str,
    generation: u64,
}

impl IdentityBinding {
    fn computed_subject_digest(&self) -> Result<Sha256Digest, AuthBusContractError> {
        let bytes = canonical_json(&IdentitySubject {
            tenant_id: &self.tenant_id,
            workspace_id: &self.workspace_id,
            agent_id: &self.agent_id,
            service_id: &self.service_id,
            node_id: &self.node_id,
            generation: self.generation,
        })?;
        Ok(domain_digest("basil-identity-subject", &bytes))
    }

    fn validate_peer(&self) -> Result<(), AuthBusContractError> {
        match &self.peer {
            IdentityPeerEvidence::LinuxPeer {
                agentd_generation,
                launch_nonce_sha256,
                pid_start_time_ticks,
                pidfd_bound,
                ..
            } => {
                if *agentd_generation != self.generation {
                    return Err(error(
                        "Linux peer generation does not match identity generation",
                    ));
                }
                if launch_nonce_sha256 != &self.launch_nonce_sha256 {
                    return Err(error(
                        "Linux peer launch nonce does not match identity launch nonce",
                    ));
                }
                validate_nonzero(*agentd_generation, "agentd generation")?;
                validate_digest(launch_nonce_sha256, "peer launch nonce")?;
                validate_nonzero(*pid_start_time_ticks, "peer start time")?;
                if !pidfd_bound {
                    return Err(error("Linux peer must carry pidfd/start-time binding"));
                }
            }
            IdentityPeerEvidence::MacAuditToken { token_sha256 } => {
                validate_digest(token_sha256, "macOS audit token")?;
            }
            IdentityPeerEvidence::ServiceUidBridge { service_uid_sha256 } => {
                validate_digest(service_uid_sha256, "service UID bridge")?;
            }
            IdentityPeerEvidence::SameUidOnly => {
                return Err(error(
                    "same-UID evidence cannot establish per-agent identity",
                ));
            }
        }
        Ok(())
    }

    /// Validate identity claims and every required generation/epoch/fence.
    pub fn validate(&self) -> Result<(), AuthBusContractError> {
        if self.schema_version != AUTHBUS_B1_CONTRACT_SCHEMA_VERSION {
            return Err(error("unsupported B1 identity schema version"));
        }
        if self.authority {
            return Err(error("B1 identity binding cannot carry authority"));
        }
        for (label, value) in [
            ("identity binding id", self.binding_id.as_str()),
            ("tenant id", self.tenant_id.as_str()),
            ("workspace id", self.workspace_id.as_str()),
            ("agent id", self.agent_id.as_str()),
            ("service id", self.service_id.as_str()),
            ("node id", self.node_id.as_str()),
            ("identity session id", self.session_id.as_str()),
            ("identity operation", self.operation.as_str()),
            ("identity key id", self.key_id.as_str()),
            ("identity audience", self.audience.as_str()),
        ] {
            validate_id(value, label)?;
        }
        for (label, value) in [
            ("identity launch nonce", &self.launch_nonce_sha256),
            ("identity nonce", &self.nonce_sha256),
            ("identity capability", &self.capability_digest),
            ("identity intent", &self.intent_digest),
            ("identity transcript", &self.transcript_digest),
            ("identity policy", &self.policy_digest),
            (
                "identity SecretRef allowlist",
                &self.secret_ref_allowlist_digest,
            ),
            ("identity HNL attestation", &self.hnl_attestation_digest),
            ("identity service identity", &self.service_identity_digest),
            ("identity subject", &self.subject_digest),
            ("identity fencing token", &self.fencing_token_sha256),
        ] {
            validate_digest(value, label)?;
        }
        for (label, value) in [
            ("identity generation", self.generation),
            ("identity epoch", self.epoch),
            ("identity authority epoch", self.authority_epoch),
            ("identity owner epoch", self.owner_epoch),
        ] {
            validate_nonzero(value, label)?;
        }
        validate_window(self.not_before_unix_seconds, self.expires_at_unix_seconds)?;
        validate_nonzero(self.issued_at_unix_seconds, "identity issued timestamp")?;
        if self.issued_at_unix_seconds < self.not_before_unix_seconds
            || self.issued_at_unix_seconds >= self.expires_at_unix_seconds
        {
            return Err(error(
                "identity issued timestamp is outside its validity window",
            ));
        }
        let expected_subject = self.computed_subject_digest()?;
        if self.subject_digest != expected_subject {
            return Err(error("identity subject digest mismatch"));
        }
        self.validate_peer()
    }

    /// Canonical bytes for the identity bridge; unknown fields are rejected by
    /// serde and invalid claims cannot be encoded.
    pub fn canonical_bytes(&self) -> Result<Vec<u8>, AuthBusContractError> {
        self.validate()?;
        canonical_json(self)
    }

    /// Domain-separated digest of the validated identity claims.
    pub fn digest(&self) -> Result<Sha256Digest, AuthBusContractError> {
        Ok(domain_digest(
            &contract_domain("basil-identity-binding"),
            &self.canonical_bytes()?,
        ))
    }
}

#[cfg(test)]
#[path = "authbus_b1_tests.rs"]
mod tests;
