//! Product-safe ranking of candidates generated by the canonical memory owner.
//!
//! This adapter deliberately does not reinterpret an owner's aggregate score as
//! a lexical, vector, graph or freshness score. The physical owner generates and
//! revalidates candidates; this module validates, binds and deterministically
//! ranks that bounded observation without gaining write authority.

use std::collections::BTreeSet;
use std::error::Error as StdError;
use std::fmt;

use codex_hepta_cognitive_types::MemoryRecord;
use codex_hepta_cognitive_types::RecordState;
use codex_hepta_types::AuthorityPosture;
use codex_hepta_types::Digest32;
use codex_hepta_types::StableId;

pub const MAX_OWNER_RANK_CANDIDATES: usize = 512;
pub const MAX_OWNER_RANK_RESULTS: usize = 16;

const REQUEST_DOMAIN: &[u8] = b"hepta.memory.retrieval.owner-rank.request.v1";
const RECEIPT_DOMAIN: &[u8] = b"hepta.memory.retrieval.owner-rank.receipt.v1";

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum OwnerEvidenceChannelV1 {
    Lexical,
    Entity,
    GraphOneHop,
    Recency,
    Temporal,
    Causal,
    Procedural,
    ContradictionSupport,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnerRankCandidateV1 {
    pub record: MemoryRecord,
    pub snapshot_digest: Digest32,
    pub owner_score: u64,
    /// Digest of the owner observation/support from which this candidate came.
    pub support_digest: Digest32,
    /// Canonical evidence classes observed by the physical owner.
    pub evidence_channels: Vec<OwnerEvidenceChannelV1>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnerRankRequestV1 {
    pub query_id: StableId,
    pub query_digest: Digest32,
    pub snapshot_digest: Digest32,
    pub maximum_results: usize,
    pub candidates: Vec<OwnerRankCandidateV1>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnerRankResultV1 {
    pub record_id: StableId,
    pub record_digest: Digest32,
    pub owner_score: u64,
    pub support_digest: Digest32,
    pub evidence_channels: Vec<OwnerEvidenceChannelV1>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnerRankReceiptV1 {
    pub query_id: StableId,
    pub snapshot_digest: Digest32,
    pub results: Vec<OwnerRankResultV1>,
    pub omitted_count: usize,
    pub request_binding_digest: Digest32,
    pub receipt_digest: Digest32,
    pub authority: AuthorityPosture,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OwnerRankErrorV1 {
    EmptyDigest(&'static str),
    InvalidMaximumResults,
    CandidateLimitExceeded,
    DuplicateRecord(String),
    SnapshotMismatch(String),
    InvalidRecord(String),
    TombstoneRecord(String),
    EmptyEvidenceChannels(String),
    DuplicateEvidenceChannel(String),
}

impl fmt::Display for OwnerRankErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{self:?}")
    }
}

impl StdError for OwnerRankErrorV1 {}

pub fn rank_owner_candidates(
    request: OwnerRankRequestV1,
) -> Result<OwnerRankReceiptV1, OwnerRankErrorV1> {
    validate_request(&request)?;
    let request_binding_digest = request_binding_digest(&request);

    let mut results = request
        .candidates
        .iter()
        .map(|candidate| OwnerRankResultV1 {
            record_id: candidate.record.record_id.clone(),
            record_digest: candidate.record.record_digest(),
            owner_score: candidate.owner_score,
            support_digest: candidate.support_digest,
            evidence_channels: canonical_evidence_channels(&candidate.evidence_channels),
        })
        .collect::<Vec<_>>();
    results.sort_by(|left, right| {
        right
            .owner_score
            .cmp(&left.owner_score)
            .then_with(|| left.record_id.cmp(&right.record_id))
    });
    let omitted_count = results.len().saturating_sub(request.maximum_results);
    results.truncate(request.maximum_results);

    let mut bytes = Vec::new();
    bytes.extend_from_slice(RECEIPT_DOMAIN);
    push_id(&mut bytes, &request.query_id);
    push_digest(&mut bytes, request.snapshot_digest);
    push_digest(&mut bytes, request_binding_digest);
    push_len(&mut bytes, results.len());
    push_len(&mut bytes, omitted_count);
    for result in &results {
        push_id(&mut bytes, &result.record_id);
        push_digest(&mut bytes, result.record_digest);
        push_u64(&mut bytes, result.owner_score);
        push_digest(&mut bytes, result.support_digest);
        push_evidence_channels(&mut bytes, &result.evidence_channels);
    }
    bytes.extend_from_slice(&[0]);

    Ok(OwnerRankReceiptV1 {
        query_id: request.query_id,
        snapshot_digest: request.snapshot_digest,
        results,
        omitted_count,
        request_binding_digest,
        receipt_digest: Digest32::of_bytes(&bytes),
        authority: AuthorityPosture::DENY_ALL,
    })
}

fn validate_request(request: &OwnerRankRequestV1) -> Result<(), OwnerRankErrorV1> {
    if request.query_digest.is_zero() {
        return Err(OwnerRankErrorV1::EmptyDigest("query"));
    }
    if request.snapshot_digest.is_zero() {
        return Err(OwnerRankErrorV1::EmptyDigest("snapshot"));
    }
    if request.maximum_results == 0 || request.maximum_results > MAX_OWNER_RANK_RESULTS {
        return Err(OwnerRankErrorV1::InvalidMaximumResults);
    }
    if request.candidates.len() > MAX_OWNER_RANK_CANDIDATES {
        return Err(OwnerRankErrorV1::CandidateLimitExceeded);
    }
    let mut seen = BTreeSet::new();
    for candidate in &request.candidates {
        if candidate.snapshot_digest != request.snapshot_digest {
            return Err(OwnerRankErrorV1::SnapshotMismatch(
                candidate.record.record_id.to_string(),
            ));
        }
        candidate
            .record
            .validate()
            .map_err(|error| OwnerRankErrorV1::InvalidRecord(error.to_string()))?;
        if candidate.record.state != RecordState::Live {
            return Err(OwnerRankErrorV1::TombstoneRecord(
                candidate.record.record_id.to_string(),
            ));
        }
        if candidate.support_digest.is_zero() {
            return Err(OwnerRankErrorV1::EmptyDigest("candidate_support"));
        }
        if candidate.evidence_channels.is_empty() {
            return Err(OwnerRankErrorV1::EmptyEvidenceChannels(
                candidate.record.record_id.to_string(),
            ));
        }
        let mut evidence_channels = BTreeSet::new();
        for channel in &candidate.evidence_channels {
            if !evidence_channels.insert(*channel) {
                return Err(OwnerRankErrorV1::DuplicateEvidenceChannel(
                    candidate.record.record_id.to_string(),
                ));
            }
        }
        if !seen.insert(candidate.record.record_id.clone()) {
            return Err(OwnerRankErrorV1::DuplicateRecord(
                candidate.record.record_id.to_string(),
            ));
        }
    }
    Ok(())
}

fn request_binding_digest(request: &OwnerRankRequestV1) -> Digest32 {
    let mut candidates = request.candidates.iter().collect::<Vec<_>>();
    candidates.sort_by(|left, right| left.record.record_id.cmp(&right.record.record_id));
    let mut bytes = Vec::new();
    bytes.extend_from_slice(REQUEST_DOMAIN);
    push_id(&mut bytes, &request.query_id);
    push_digest(&mut bytes, request.query_digest);
    push_digest(&mut bytes, request.snapshot_digest);
    push_len(&mut bytes, request.maximum_results);
    push_len(&mut bytes, candidates.len());
    for candidate in candidates {
        push_id(&mut bytes, &candidate.record.record_id);
        push_digest(&mut bytes, candidate.record.record_digest());
        push_digest(&mut bytes, candidate.snapshot_digest);
        push_u64(&mut bytes, candidate.owner_score);
        push_digest(&mut bytes, candidate.support_digest);
        let evidence_channels = canonical_evidence_channels(&candidate.evidence_channels);
        push_evidence_channels(&mut bytes, &evidence_channels);
    }
    Digest32::of_bytes(&bytes)
}

fn canonical_evidence_channels(
    channels: &[OwnerEvidenceChannelV1],
) -> Vec<OwnerEvidenceChannelV1> {
    let mut channels = channels.to_vec();
    channels.sort();
    channels
}

fn push_evidence_channels(bytes: &mut Vec<u8>, channels: &[OwnerEvidenceChannelV1]) {
    push_len(bytes, channels.len());
    for channel in channels {
        bytes.push(match channel {
            OwnerEvidenceChannelV1::Lexical => 0,
            OwnerEvidenceChannelV1::Entity => 1,
            OwnerEvidenceChannelV1::GraphOneHop => 2,
            OwnerEvidenceChannelV1::Recency => 3,
            OwnerEvidenceChannelV1::Temporal => 4,
            OwnerEvidenceChannelV1::Causal => 5,
            OwnerEvidenceChannelV1::Procedural => 6,
            OwnerEvidenceChannelV1::ContradictionSupport => 7,
        });
    }
}

fn push_id(bytes: &mut Vec<u8>, value: &StableId) {
    let raw = value.as_str().as_bytes();
    push_len(bytes, raw.len());
    bytes.extend_from_slice(raw);
}

fn push_digest(bytes: &mut Vec<u8>, value: Digest32) {
    bytes.extend_from_slice(value.as_array());
}

fn push_len(bytes: &mut Vec<u8>, value: usize) {
    push_u64(bytes, u64::try_from(value).unwrap_or(u64::MAX));
}

fn push_u64(bytes: &mut Vec<u8>, value: u64) {
    bytes.extend_from_slice(&value.to_be_bytes());
}

#[cfg(test)]
#[path = "owner_rank_tests.rs"]
mod tests;
